### ISSUE TITLE
如果将文件加密上传,然后用普通的方式下载

### ISSUE THREAD

**Issue by chijiao** [GangZhuo/baidupcs#10]
如果将文件加密上传,然后用普通的方式下载,请问该用什么方式进行解密?
这个问题主要是考虑到这种情况. 我需要把爱情电影进行加密上传到百度云, 然后下载的时候,用百度云管家下载. 这个下载速度比较快. 因为上传是经过加密的.需要解密, 请问有没有相关的方法进行解密?

另外一个问题, 如果百度云网盘的网站接口发生了改变, 是不是需要重新编译源代码?

**Comment by GangZhuo** [comment]
'pcs encode -d ~/download/xxx.mp4 ~/music/xxx.mp4'  将会使用上下文中的 密钥来解密。

**Comment by GangZhuo** [comment]
网站接口发生变化的话，如果旧接口还能使用，则不需要做任何事情，如果旧接口已经不能使用了，那么需要重新实现新接口的，重新实现后是需要重新编译的。
