### ISSUE TITLE
能否添加在线看视频的功能

### ISSUE THREAD

**Issue by redapple0204** [GangZhuo/BaiduPCS#102]
通过调用本地播放器。

**Comment by wnpllrzodiac** [comment]
原先没有限速的时候，我实现了win32 安卓平台的类似功能。直接播放在线媒体文件。现在限速下，如果要速度快，只能采用多线程下载方式，复杂度大了。如果买了vip，倒是另说了

**Comment by Droid-MAX** [comment]
这只是一个简单的百度网盘命令行工具，我只用来上传下载及管理网盘文件的用途，如果你还想要什么其他例如在线播放媒体文件的话，那你还是适合使用官方提供的客户端。。。

**Comment by sqc1999** [comment]
宣传一下我的项目[HackingBaidu/BaiduPanMount](/HackingBaidu/BaiduPanMount)，将百度云挂载到本地盘符，理论上也支持视频播放，不过因为是单线程下载，速度不是很理想，bdrip 1080p带不动

**Comment by GangZhuo** [comment]
no plan
