### ISSUE TITLE
Failed to send sms

### ISSUE THREAD

**Issue by louyong0571** [GangZhuo/BaiduPCS#107]
$ pcs login --username=xxxx
Password:
The captcha image at /home/ubuntu/.pcs/captcha.gif.
Please input the captcha code: RSIW
Login Failed: Failed to send sms:
就失败了

**Comment by hanandjun** [comment]
验证码输入了吗

**Comment by hanandjun** [comment]
@louyong0571 验证码输入了吗?

**Comment by louyong0571** [comment]
@hanandjun 输入了，后来发现只要是开通了会员的就会有这个问题，没开通会员的是ok的。

**Comment by huangyisan** [comment]
我也是卡这一步。输入了验证码，说是要手机验证。但是验证短信也发给我了。但我不知道要怎么处理。我的不是会员

**Comment by Droid-MAX** [comment]
解绑手机号

**Comment by GangZhuo** [comment]
via https://github.com/GangZhuo/BaiduPCS/commit/e1c2a1935e57e0eb167fa735d02db72c40021ca5
