### ISSUE TITLE
不能上传目录

### ISSUE THREAD

**Issue by chijiao** [GangZhuo/baidupcs#11]
我觉得这个工具很好,下载没问题,可是目录上传不行.

pcs synch -u localdir /
Scanning local file system...
Completed
Fetching net disk file list...
Fetch 9                     
Completed
Comparing...

Completed

Download: off, Upload: on, Confuse: off, Equal: off
Printing|Synching...
Completed
       Local File OP Net Disk File
----------------------------------

Statistic:
----------------------------------
Need Download: 9, Need Upload: 0
Confuse: 0, Equal: 0, Other: 0
Total: 9, Fail: 0

Notes:
  <- means the right file will download into 
     the local file system. 
  -> means the left file will upload into the disk. 
  == means left file same as right file. 
  >< means confuse, don't known how to. 

还是我的用法有问题, 正常情况下,应该是可以的啊

**Comment by GangZhuo** [comment]
试试：
    pcs mkdir /localdir
    pcs synch -ur localdir /localdir

**Comment by chijiao** [comment]
还是一样的,

pcs mkdir /Simply.The.Best.2012.HDRip.720p
pcs synch -ur Simply.The.Best.2012.HDRip.720p /Simply.The.Best.2012.HDRip.720p
Scanning local file system...
Completed
Fetching net disk file list...
Completed
Comparing...
Completed

Download: off, Upload: on, Confuse: off, Equal: off
Printing|Synching...
Completed
       Local File OP Net Disk File
----------------------------------


Statistic:
----------------------------------
Need Download: 0, Need Upload: 0
Confuse: 0, Equal: 0, Other: 0
Total: 0, Fail: 0


Notes:
  <- means the right file will download into 
     the local file system. 
  -> means the left file will upload into the disk. 
  == means left file same as right file. 
  >< means confuse, don't known how to.

**Comment by GangZhuo** [comment]
pcs ls /Simply.The.Best.2012.HDRip.720p  看看，看起来好像文件已经传上去了。看那个输出中有0个需要上传。还是我搞错意思了？需要能上传空的文件夹？

**Comment by chijiao** [comment]
henry@henry-xbmc:/mnt/raid/sdb1$ ls -lh Simply.The.Best.2012.HDRip.720p/
total 4.1G
-rwxrwxrwx 1 henry henry  286K Feb 19  2012 Scene 1 - Sandra Shine,Vera,Antonya.jpg
-rwxrwxrwx 1 henry henry  693M Feb 19  2012 Scene 1 - Sandra Shine,Vera,Antonya.mp4
-rwxrwxrwx 1 henry henry  238K Feb 19  2012 Scene 2 - Eve Angel and Jo.jpg
-rwxrwxrwx 1 henry henry  752M Feb 19  2012 Scene 2 - Eve Angel and Jo.mp4
-rwxrwxrwx 1 henry henry  310K Feb 19  2012 Scene 3 - Sandra Shine and Antonya.jpg
-rwxrwxrwx 1 henry henry 1014M Feb 19  2012 Scene 3 - Sandra Shine and Antonya.mp4
-rwxrwxrwx 1 henry henry  300K Feb 19  2012 Scene 4 - Vera and Eve Angel.jpg
-rwxrwxrwx 1 henry henry  950M Feb 19  2012 Scene 4 - Vera and Eve Angel.mp4
-rwxrwxrwx 1 henry henry  258K Feb 19  2012 Scene 5 - Jo and Sandra Shine.jpg
-rwxrwxrwx 1 henry henry  738M Feb 19  2012 Scene 5 - Jo and Sandra Shine.mp4
-rwxrwxrwx 1 henry henry  110K Feb 19  2012 vt128-800-front.jpg


目录不是空的哦

**Comment by GangZhuo** [comment]
在浏览器中打开百度网盘，能看到上传的文件吗？  上传时，程序会获取本地文件列表和网盘中对应文件夹的文件列表，并比较他们的最后修改时间，如果本地文件的修改时间小于网盘中文件的上传时间，则认为文件不需要重新上传。所以统计出来有0个需要上传，意思就是文件在网盘中都存在了，且是最新的。所以，需要你用 ‘pcs ls /Simply.The.Best.2012.HDRip.720p’ 来列出网盘文件，或者直接在浏览器中查看文件是否已经上传成功了。
我这边上传都正常。

**Comment by chijiao** [comment]
我没办法,刚写了一个脚本,实现上传目录.经过测试正常.

#!/bin/bash

DIR=$1

find $DIR > /tmp/${DIR}.list

cat /tmp/${DIR}.list | while read line; do
    if [ -d ${line} ]; then
        echo ${line} is dir
        # 远程建立目录
        pcs mkdir /${line}
    elif [ -f ${line} ]; then
        echo ${line} is file
        # 上传文件
        pcs upload ${line} /${line}
    fi
done

希望能给人带来帮助

**Comment by chijiao** [comment]
莫非是我RP出了问题. 你说的方法, 我测试好多次都不行. 在浏览器里面查看,文件的确没有上传上去.是空的.
我写了一个简单的脚本,用来上传目录. 配合上传文件的功能, 感觉非常的好用.
