### ISSUE TITLE
pcs/cJSON.c:1: error: stray '\239' in program

### ISSUE THREAD

**Issue by osDanielLee** [GangZhuo/BaiduPCS#110]
不知道出现这种问题普遍不？我第一次在linux上make BaiduPCS，上网查看都说是字符问题，参考了一些方法去除一些不可见字符也没有得到解决。

```
[xxx@XXXX BaiduPCS]$ make
/usr/bin/make64 MAC=64
makefile:23: "Use 'make ver=debug' to build for gdb debug."
mkdir -p bin/
cc -o bin/cJSON.o -c -fPIC -D_FILE_OFFSET_BITS=64   pcs/cJSON.c
pcs/cJSON.c:1: error: stray '\239' in program
pcs/cJSON.c:1: error: stray '\187' in program
pcs/cJSON.c:1: error: stray '\191' in program
In file included from pcs/cJSON.c:33:
pcs/cJSON.h:1: error: stray '\239' in program
pcs/cJSON.h:1: error: stray '\187' in program
pcs/cJSON.h:1: error: stray '\191' in program
make64: *** [bin/cJSON.o] Error 1
```

**Comment by GangZhuo** [comment]
转换文件编码为 utf8后试试

https://www.google.com/search?q=linux+convert+ascii+file+to+utf8&oq=linux+convert+file+to+utf8&aqs=chrome.1.69i57j0l3.15359j0j4&client=ms-android-google&sourceid=chrome-mobile&ie=UTF-8

Daniel Li <notifications@github.com>于2017年1月4日周三 下午4:11写道：

**Comment by osDanielLee** [comment]
@GangZhuo 引起原因是utf-8文件中带有BOM，使用一下指令可以除掉BOM
dd if=filewithbom of=filewithoutbom bs=1 skip=3
你可以close掉这个issue了！^_^
