### ISSUE TITLE
下载文件时断断续续，总体速度极慢，下载总耗时客户端差不多

### ISSUE THREAD

**Issue by solderwire** [GangZhuo/BaiduPCS#111]
1月6日早晨还可正常下载，中午开始下载就出现如题所示的情况，在开启100线程后，不出现任何服务器超时或拒绝连接的信息（以前下载的时候就会出现，但能正常的以高速度下载）

**Comment by Droid-MAX** [comment]
100线程，23333333

**Comment by Droid-MAX** [comment]
服务器有说不会限制你的下载线程数吗？

**Comment by GangZhuo** [comment]
设置好线程后，在开始下载。线程数不宜太多
