### ISSUE TITLE
debian下这一步太简单了

### ISSUE THREAD

**Issue by lcgogo** [GangZhuo/BaiduPCS#112]
make install #将安装到/usr/local/bin下

lichao@lichao-virtual-machine:~/BaiduPCS$ sudo make install
makefile:23: "Use 'make ver=debug' to build for gdb debug."
cp ./bin/pcs /usr/local/bin

我系统里没/usr/local/bin这个文件夹，所以这里直接把pcs给命名成bin了。

**Comment by GangZhuo** [comment]
可以手动安装的。
