### ISSUE TITLE
下载的时候file size不能get?

### ISSUE THREAD

**Issue by lcgogo** [GangZhuo/BaiduPCS#113]
[fail]            <- Playlists/diablo.wpl
      Can't get the file size.
[fail]            <- Playlists/film.wpl
      Can't get the file size.
[fail]            <- SlamDunk/SlamDunk-theendofworld.mp3
      Can't get the file size.

我用的
pcs s -du

**Comment by lcgogo** [comment]
重做一遍又好了。

**Comment by PierreTim** [comment]
同步若干文件之后就会出现这个问题，只能不断重新运行同步。

**Comment by lcgogo** [comment]
好像百度有限制，如果马上重复运行的话，就立马报错。

**Comment by Droid-MAX** [comment]
pcs的同步目录这块问题比较多

**Comment by lcgogo** [comment]
不知道是pcs的问题还是百度的问题。现在我设了个cron job，每小时更新一次。

**Comment by GangZhuo** [comment]
这个是服务器返回的错误，只能重试。
