### ISSUE TITLE
总是提示输入图形验证码

### ISSUE THREAD

**Issue by foquanlin** [GangZhuo/BaiduPCS#116]
The captcha image at /root/.pcs/captcha.gif.
Please input the captcha code: 水平
The captcha image at /root/.pcs/captcha.gif.
Please input the captcha code: ^C
[root@meilyhome tools]# ./baidu_upload.sh 
The captcha image at /root/.pcs/captcha.gif.
Please input the captcha code: 中学
The captcha image at /root/.pcs/captcha.gif.
Please input the captcha code: 诗人
The captcha image at /root/.pcs/captcha.gif.

不知道是不是secureCRT的问题,还是程序的问题
每次输入中文验证码都是不对的

**Comment by GangZhuo** [comment]
尝试最新版
