### ISSUE TITLE
建议增加用配置文件保存用户名密码自动登录功能

### ISSUE THREAD

**Issue by chijiao** [GangZhuo/BaiduPCS#118]
如题, 现在登录的时候提示手动输入用户名密码,有时候在脚本里面这样不方便. 建议增加一个配置文件,把用户名和密码保存到配置文件中, 这样就用直接自动登录了, 不需要登录的时候每次手动输入用户名和密码

另外建议增加一个使用说明文档, 把 chrome 登录网页的cookie拷贝出来, 保存到文件, 然后pcs 可以直接调用这个cookie.就避免了要登录或者出现手机验证码的情况. 虽然我知道pcs也是模拟登录web. 保存cookie.但是一直没有找到如何把 chrome 的cookie提取出来给pcs直接调用的方法

**Comment by redapple0204** [comment]
还不如直接用BDUSS呢

**Comment by sqc1999** [comment]
@chijiao 如果配置文件只是保存用户名密码的话，直接用脚本读取不是更方便吗

**Comment by chijiao** [comment]
@sqc1999 比如登录的时候, 需要手动输入用户名和密码, 用脚本不方便吧, 我在后台自动调用, 咋输用户名密码?

**Comment by sqc1999** [comment]
@chijiao 我是说从配置文件读取用户名密码的工作由脚本来做，反正很方便

**Comment by Droid-MAX** [comment]
我觉得这个issue可以close掉了
自己看看pcs login -h
另外只要是成功登陆的，保存在本地的cookies有效期1个月，所以只要不是手动注销那么在登陆成功后一个月内是无需重复进行登录操作的

或者说你们的意思是想为这个pcs做个luci界面应用？
just do it！

**Comment by GangZhuo** [comment]
no plan
