### ISSUE TITLE
上传文件的时候,一定要制定远程文件名

### ISSUE THREAD

**Issue by chijiao** [GangZhuo/baidupcs#12]
这个不一定是issue. 但是用起来不方便. 比如我要上传一个文件到远程的 / 目录下, 非要指定远程的文件名才行. 是否可以更新下, 如果远程为目录, 则默认用本地的文件名. 这样更方便一些.

**Comment by GangZhuo** [comment]
Now, you can use 'pcs upload xxx.txt /folder'

**Comment by chijiao** [comment]
经过测试, 新版本这个功能完全正常了
