### ISSUE TITLE
doc帮助文档的小问题

### ISSUE THREAD

**Issue by ljq917181927** [GangZhuo/BaiduPCS#120]
在doc目录下的那个html这个标签↓ 的account被当作网页的标签了，没显示出来。
 pcs -u<account> --urlc quota

![image](https://cloud.githubusercontent.com/assets/20370522/22341777/117288e0-e42d-11e6-9c6d-0f2eb0bf310e.png)

**Comment by GangZhuo** [comment]
Fixed.
