### ISSUE TITLE
关于pcs同步目录的问题

### ISSUE THREAD

**Issue by Droid-MAX** [GangZhuo/BaiduPCS#127]
在使用pcs同步远程目录到本地时，如果远程目录当中包含有子文件夹的话，将无法正常地把子文件夹同步到本地目录下

**Comment by FuGoGo** [comment]
相同问题

**Comment by lcgogo** [comment]
pcs synch -cdr ?你说r不管用么？

**Comment by Droid-MAX** [comment]
pcs同步目录这块没毛病，同步目录前要在本地当前目录下新建一个跟将要同步的远程目录名一样的文件夹，另外想要递归同步远程目录下的所有子目录得加上-r参数，如:pcs synch -cdr xxxx xxxx
