### ISSUE TITLE
Faied to login

### ISSUE THREAD

**Issue by leenchan** [GangZhuo/BaiduPCS#129]
8e6b208621f6:~ pcs login --username=xxxxxx --password=xxxxxx
The captcha image at /root/.pcs/captcha.gif.
GYAD
Please input the captcha code: Login Failed: Failed to send sms: 参数错误
8e6b208621f6:~#

**Comment by lcgogo** [comment]
这是验证码没输对吧。

**Comment by GangZhuo** [comment]
尝试最新版

**Comment by GangZhuo** [comment]
via https://github.com/GangZhuo/BaiduPCS/commit/e1c2a1935e57e0eb167fa735d02db72c40021ca5
