### ISSUE TITLE
大文件上传,经常出现超时的错误.

### ISSUE THREAD

**Issue by chijiao** [GangZhuo/baidupcs#13]
前 99% 的速度, 上传的速度有异常的稳定, 如果中途有超时情况, 重试就可以过去. 但是每次到了99% 以后, 就很容易出现如下的错误提示. 然后就一直卡着不动.一直不停的重试.

Upload slice failed, retry delay 10 second, tid: 0x7f21b123d700. message: Timeout was reached: http://c.pcs.baidu.com/rest/2.0/pcs/file?method=upload&type=tmpfile&app_id=250528&BDUSS=ZvSTh-T1NpVDU2MWl0ekN-UDk2N1FLVUNsaEV0akM3TVJ-UHRvNTNaaUFWTjlVQVFBQUFBJCQAAAAAAAAAAAEAAAAqEAU4zMazr7XEUVEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDHt1SAx7dUdn

如上, 如果上传超过12G或者更大的文件. 上传完成以后,就会出现这个错误. 而且重试了很多次,一直都提示同样的错误.

其实已经上传了99.99%. 

重复出现如下错误.

---
Upload slice failed, retry delay 10 second, tid: 0x7f21b123d700. message: Timeout was reached: http://c.pcs.baidu.com/rest/2.0/pcs/file?method=upload&type=tmpfile&app_id=250528&BDUSS=ZvSTh-T1NpVDU2MWl0ekN-UDk2N1FLVUNsaEV0akM3TVJ-UHRvNTNaaUFWTjlVQVFBQUFBJCQAAAAAAAAAAAEAAAAqEAU4zMazr7XEUVEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDHt1SAx7dUdn
Upload slice failed, retry delay 10 second, tid: 0x7f2166301700. message: Timeout was reached: http://c.pcs.baidu.com/rest/2.0/pcs/file?method=upload&type=tmpfile&app_id=250528&BDUSS=ZvSTh-T1NpVDU2MWl0ekN-UDk2N1FLVUNsaEV0akM3TVJ-UHRvNTNaaUFWTjlVQVFBQUFBJCQAAAAAAAAAAAEAAAAqEAU4zMazr7XEUVEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDHt1SAx7dUdn
Upload slice failed, retry delay 10 second, tid: 0x7f21a0909700. message: Timeout was reached: http://c.pcs.baidu.com/rest/2.0/pcs/file?method=upload&type=tmpfile&app_id=250528&BDUSS=ZvSTh-T1NpVDU2MWl0ekN-UDk2N1FLVUNsaEV0akM3TVJ-UHRvNTNaaUFWTjlVQVFBQUFBJCQAAAAAAAAAAAEAAAAqEAU4zMazr7XEUVEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDHt1SAx7dUdn
Upload slice failed, retry delay 10 second, tid: 0x7f21b123d700. message: Timeout was reached: http://c.pcs.baidu.com/rest/2.0/pcs/file?method=upload&type=tmpfile&app_id=250528&BDUSS=ZvSTh-T1NpVDU2MWl0ekN-UDk2N1FLVUNsaEV0akM3TVJ-UHRvNTNaaUFWTjlVQVFBQUFBJCQAAAAAAAAAAAEAAAAqEAU4zMazr7XEUVEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDHt1SAx7dUdn
Upload slice failed, retry delay 10 second, tid: 0x7f2166301700. message: Timeout was reached: http://c.pcs.baidu.com/rest/2.0/pcs/file?method=upload&type=tmpfile&app_id=250528&BDUSS=ZvSTh-T1NpVDU2MWl0ekN-UDk2N1FLVUNsaEV0akM3TVJ-UHRvNTNaaUFWTjlVQVFBQUFBJCQAAAAAAAAAAAEAAAAqEAU4zMazr7XEUVEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDHt1SAx7dUdn
Upload slice failed, retry delay 10 second, tid: 0x7f21a0909700. message: Timeout was reached: http://c.pcs.baidu.com/rest/2.0/pcs/file?method=upload&type=tmpfile&app_id=250528&BDUSS=ZvSTh-T1NpVDU2MWl0ekN-UDk2N1FLVUNsaEV0akM3TVJ-UHRvNTNaaUFWTjlVQVFBQUFBJCQAAAAAAAAAAAEAAAAqEAU4zMazr7XEUVEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDHt1SAx7dUdn
Upload slice failed, retry delay 10 second, tid: 0x7f21b123d700. message: Timeout was reached: http://c.pcs.baidu.com/rest/2.0/pcs/file?method=upload&type=tmpfile&app_id=250528&BDUSS=ZvSTh-T1NpVDU2MWl0ekN-UDk2N1FLVUNsaEV0akM3TVJ-UHRvNTNaaUFWTjlVQVFBQUFBJCQAAAAAAAAAAAEAAAAqEAU4zMazr7XEUVEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDHt1SAx7dUdn
Upload slice failed, retry delay 10 second, tid: 0x7f2166301700. message: Timeout was reached: http://c.pcs.baidu.com/rest/2.0/pcs/file?method=upload&type=tmpfile&app_id=250528&BDUSS=ZvSTh-T1NpVDU2MWl0ekN-UDk2N1FLVUNsaEV0akM3TVJ-UHRvNTNaaUFWTjlVQVFBQUFBJCQAAAAAAAAAAAEAAAAqEAU4zMazr7XEUVEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDHt1SAx7dUdn
Upload slice failed, retry delay 10 second, tid: 0x7f21a0909700. message: Timeout was reached: http://c.pcs.baidu.com/rest/2.0/pcs/file?method=upload&type=tmpfile&app_id=250528&BDUSS=ZvSTh-T1NpVDU2MWl0ekN-UDk2N1FLVUNsaEV0akM3TVJ-UHRvNTNaaUFWTjlVQVFBQUFBJCQAAAAAAAAAAAEAAAAqEAU4zMazr7XEUVEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDHt1SAx7dUdn
Upload slice failed, retry delay 10 second, tid: 0x7f21b123d700. message: Timeout was reached: http://c.pcs.baidu.com/rest/2.0/pcs/file?method=upload&type=tmpfile&app_id=250528&BDUSS=ZvSTh-T1NpVDU2MWl0ekN-UDk2N1FLVUNsaEV0akM3TVJ-UHRvNTNaaUFWTjlVQVFBQUFBJCQAAAAAAAAAAAEAAAAqEAU4zMazr7XEUVEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIDHt1SAx7dUdn

---

**Comment by chijiao** [comment]
我一直稳定在 3.5m/s的上传速度. 如果你需要提供更多的测试数据. 我可以提供. 看看怎么样才能打印输出更多的 debug 信息

**Comment by GangZhuo** [comment]
在本地文件所在的目录下，会有一个对应的 '.slice' 后缀文件，这个文件存储了分片数据和其上传状态等信息，能压缩后发到 gang.zhuo@gmail.com 吗？

**Comment by chijiao** [comment]
已发,请查收

**Comment by GangZhuo** [comment]
收到

**Comment by GangZhuo** [comment]
need test

**Comment by chijiao** [comment]
经过上传一个 22G 的文件进行测试来看, 初步正常, 我后续将进行更多的超大文件测试.
