### ISSUE TITLE
Windows下编译问题

### ISSUE THREAD

**Issue by FuGoGo** [GangZhuo/BaiduPCS#138]
**最终目录结构有误**
>**需要把deps目录放入BaiduPcs目录下**

**编译后仍无法运行**

>**缺少nghttp2.dll,需要到 http://windows.php.net/downloads/php-sdk/deps/vc14/x86/ 下载[nghttp2](http://windows.php.net/downloads/php-sdk/deps/vc14/x86/)放入生成pcs.exe的目录**

>希望能够及时更新文档

**Comment by GangZhuo** [comment]
嗯，php.net 中的库最近需要下载 nghttp2 了。
近期，计划编译了一个 curl 和 openssl 的静态包。

**Comment by ywyywy** [comment]
请问，执行编译操作具体要做什么?要改东西吗？我deps放到根目录，点调试，提示我缺少什么。。。

**Comment by GangZhuo** [comment]
跟随最新的 README.md ，使用自己编译的静态 libcurl 了
