### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by aliluys** [GangZhuo/BaiduPCS#139]
这是log:
C:\projects\baidupcs\BaiduPCS\pcs\pcs_defs.h:4:23: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
                       ^
compilation terminated.
Process terminated with status 1 (0 minute(s), 0 second(s))
1 error(s), 0 warning(s) (0 minute(s), 0 second(s))
你好。我是一个新学者，一开始对于C的编译没有概念，这是学习了一点粗浅的知识和找到codeblocks后的尝试，但是curl这个头文件一直显示没有路径，希望有前辈可以教一下，我也会在google上继续找的，不过目前找到的太偏门，不是解决方案，多谢！

**Comment by aliluys** [comment]
我尝试预编译版本，成功了，但是还希望能有人能告知如何解决以上问题，感激不尽。另外请问百度网盘的昵称是中文无法登陆吗？

**Comment by FuGoGo** [comment]
请看我提出的另一issue，在此issue下方
希望再提问题前可以查看别人是否已经提出
https://github.com/GangZhuo/BaiduPCS/issues/138

**Comment by aliluys** [comment]
不好意思 那位仁兄正好在我前面提出了
