### ISSUE TITLE
建议上传文件的时候,增加命令行参数进行加密上传的功能.

### ISSUE THREAD

**Issue by chijiao** [GangZhuo/baidupcs#14]
感谢开发者的努力. 我一直在测试这个,感觉很好用. 但是我觉得有点需要改进下.就是在上传文件的时候, 可以通过命令行指定加密方式. 
比如很多人有这种需求, 上传A文件的时候, 不加密上传. 上传B文件的时候, 又需要加密上传. 如果不能在命令行参数中控制, 每次上传完毕,都需要修改一次配置文件. 比较麻烦.
建议在上传文件的时候, 可以通过参数,手动指定是否加密上传

因为经常需要批量上传文件和文件夹. 每次都需要修改配置文件, 改来改去很麻烦

**Comment by GangZhuo** [comment]
拿一下最新代码。  
现在你可以这么做：
  cp ~/.pcs/pcs.context ~/.pcs/pcs-secure.context
  pcs set --secure_enable=true --context=~/.pcs/pcs-secure.context

不需要加密上传时，执行 pcs upload ... 或者 pcs upload ... --context=~/.pcs/pcs.context
当需要加密上传时，执行 pcs upload ... --context=~/.pcs/pcs-secure.context

**Comment by GangZhuo** [comment]
思想就是：提供两个上下文文件，一个配置为无需加密，另一个配置为需要加密。在上传文件时分别指定不同的上下文文件。

**Comment by chijiao** [comment]
这种方式应该也能解决这个问题了, 另外建议更新一下使用说明文档. 有些功能在文档里面没有写出来
