### ISSUE TITLE
windows编译，出现错误提示

### ISSUE THREAD

**Issue by ywyywy** [GangZhuo/BaiduPCS#140]
新手一枚。deps已放到baiduPCS根目录下。打开baidupcs.sln，点调试-开始调试
结果提示：
1>------ 已启动生成: 项目: BaiduPCS_DLL, 配置: Debug Win32 ------
1>    正在创建库 C:\Users\lenovo\BaiduPCS\Debug\BaiduPCS.lib 和对象 C:\Users\lenovo\BaiduPCS\Debug\BaiduPCS.exp
1>libcurl_a.lib(zutil.obj) : warning LNK4099: 未找到 PDB“zlib.pdb”(使用“libcurl_a.lib(zutil.obj)”或在“C:\Users\lenovo\BaiduPCS\Debug\zlib.pdb”中寻找)；正在链接对象，如同没有调试信息一样
1>libcurl_a.lib(inffast.obj) : warning LNK4099: 未找到 PDB“zlib.pdb”(使用“libcurl_a.lib(inffast.obj)”或在“C:\Users\lenovo\BaiduPCS\Debug\zlib.pdb”中寻找)；正在链接对象，如同没有调试信息一样
1>libcurl_a.lib(inftrees.obj) : warning LNK4099: 未找到 PDB“zlib.pdb”(使用“libcurl_a.lib(inftrees.obj)”或在“C:\Users\lenovo\BaiduPCS\Debug\zlib.pdb”中寻找)；正在链接对象，如同没有调试信息一样
1>libcurl_a.lib(inflate.obj) : warning LNK4099: 未找到 PDB“zlib.pdb”(使用“libcurl_a.lib(inflate.obj)”或在“C:\Users\lenovo\BaiduPCS\Debug\zlib.pdb”中寻找)；正在链接对象，如同没有调试信息一样
1>libcurl_a.lib(crc32.obj) : warning LNK4099: 未找到 PDB“zlib.pdb”(使用“libcurl_a.lib(crc32.obj)”或在“C:\Users\lenovo\BaiduPCS\Debug\zlib.pdb”中寻找)；正在链接对象，如同没有调试信息一样
1>libcurl_a.lib(adler32.obj) : warning LNK4099: 未找到 PDB“zlib.pdb”(使用“libcurl_a.lib(adler32.obj)”或在“C:\Users\lenovo\BaiduPCS\Debug\zlib.pdb”中寻找)；正在链接对象，如同没有调试信息一样
1>  BaiduPCS_DLL.vcxproj -> C:\Users\lenovo\BaiduPCS\Debug\BaiduPCS.dll
1>  BaiduPCS_DLL.vcxproj -> C:\Users\lenovo\BaiduPCS\Debug\BaiduPCS.pdb (Full PDB)
1>  已复制         1 个文件。
1>  已复制         1 个文件。
1>  已复制         1 个文件。
========== 生成: 成功 1 个，失败 0 个，最新 0 个，跳过 0 个 ==========

这样该怎么做？

**Comment by FuGoGo** [comment]
应该是使用 生成->(生成解决方案/重新生成解决方案) 吧
使用libcurl_a.lib，curl的库文件夹应该需要改名为 curl
问题仍存在可以向作者发邮件或上网搜索解决方法
**我也是新手，不咋会这个东西**

**Comment by aliluys** [comment]
不应该是打开sln文件吗，自己编译需要加一个依赖文件，看issue138,或者可以直接用预编译版本。

**Comment by ywyywy** [comment]
是打开sln，不过不清楚教程写的编译该怎么做。搜到有的是点调试。
使用生成，还是一样的错误提示。改文件夹名那句没看懂 ？_？
按138提示已经放到根目录。预编译版本闪退，不知道是不是因为64位。net4.0能用，不过装了那么久的vs 2015，想弄明白是哪出问题

**Comment by aliluys** [comment]
不是闪退…，你要在cmd里运行的，不能简单双击，你cd“pcs.exe"到目录，然后用pcs命令就行了

**Comment by aliluys** [comment]
你是在酷市场看到这个的吗

**Comment by FuGoGo** [comment]
可以把pcs的目录添加到环境变量 然后随便哪个地方都可以直接使用 pcs命令了
至于编译有问题 在issue上不太方便 可以使用邮箱与我交流一下[点此](fushy741@gmail.com)

**Comment by ywyywy** [comment]
哦哦，了解了。跟adb一样的用法。
在酷安和悠二上看到了的。
谢谢两位！

**Comment by aliluys** [comment]
不谢～不过悠二是什么，没搜索到

**Comment by ywyywy** [comment]
U2动漫花园。分享番剧音乐 etc 的地方

**Comment by GangZhuo** [comment]
跟随最新的 README.md 重试看看。
