### ISSUE TITLE
远程文件路径有空格,会无法下载.

### ISSUE THREAD

**Issue by giveup** [GangZhuo/BaiduPCS#145]
例子:
pcs download /sync/sample .txt ~/sync/sample.txt
同样,本地路径有空格也无法下载.
可能是需要转义?

**Comment by giveup** [comment]
#109 和这个issue类似.
目前折中的办法还是手动修改一下文件名.

**Comment by urain39** [comment]
Linux下这种问题都是手动加上引号，单引号（' '），双引号("")都可以。

**Comment by GangZhuo** [comment]
需要使用双引号
