### ISSUE TITLE
最新版无法登陆？请解答。

### ISSUE THREAD

**Issue by AdairChan** [GangZhuo/BaiduPCS#147]
Ubuntu16.04编译安装完后，使用pcs login命令进行登陆；
输入账号和密码之后报错：
Error: Couldn't resolve host name: http://pan.baidu.com/disk/home
请教一下是什么问题？

**Comment by aliluys** [comment]
我估计百度把这个封掉了，我是windows也登陆不了了。

**Comment by AdairChan** [comment]
@aliluys 你之前是可以用的是吗？

**Comment by GangZhuo** [comment]
try latest version

**Comment by AdairChan** [comment]
更新版本后可以登陆了
