### ISSUE TITLE
作者您好，关于登录问题

### ISSUE THREAD

**Issue by zsakvo** [GangZhuo/BaiduPCS#148]
Ubuntu16.04.2  从您最新的源码编译，登录时提示 Login Failed: error: 5 See popped out window. 
请问是什么情况呢？（没找到从哪里看错误码……）
![_001](https://cloud.githubusercontent.com/assets/25399519/23706557/ab7cc306-0449-11e7-9d26-ec8dd1dbb3ad.png)

**Comment by KyleRicardo** [comment]
同，一直登陆不上，win，C#，openwrt，Linux各种端都是错误代码5，希望给出原因！

**Comment by GangZhuo** [comment]
在出差，回来后看看。

**Comment by AdairChan** [comment]
一样的问题。。。

**Comment by zelda0079** [comment]
请问作者可否把BaiduPCS_NET 也一起更新? 另外, 
如果帐号需要验证身份登入就会无法登入
例如手机或邮箱验证那种
我有1个帐号一定要验证无法取消

**Comment by zichenshan** [comment]
同样的问题，无法登录。

**Comment by 11liju** [comment]
今天开始无法下载，之后logout，再login，也是同样问题，无法登录

**Comment by G-Joker** [comment]
我也试一下吧

**Comment by readlnh** [comment]
貌似登录那加密了。。

**Comment by G-Joker** [comment]
加密就难搞了

**Comment by GangZhuo** [comment]
登录早就加密了，不过不加密也可以登录，有可能现在强制必须加密了。

G-Joker2 <notifications@github.com>于2017年3月10日周五 下午8:54写道：

**Comment by zelda0079** [comment]
所以现在是很难修复的意思吗?

**Comment by Jona-lee** [comment]
$ pcs login
User Name: xxxx
Password: 
Login Failed: error: 5 See popped out window.
遇到一样的问题，无法登录，popped out window也没有看到有

**Comment by derekhe** [comment]
有一个朋友已经解决了问题了：
请看这里，亲测可用
https://github.com/xdibin/BaiduPCS/tree/httpd

**Comment by GangZhuo** [comment]
fixed
