### ISSUE TITLE
无法登录和下载了

### ISSUE THREAD

**Issue by 11liju** [GangZhuo/BaiduPCS#150]
下载的时候数字不变，处于假死状态，之后登出，就再也无法登录，显示Login Failed: error: 5 See popped out window.

**Comment by 11liju** [comment]
用的是macOS

**Comment by jumpx1** [comment]
我用linux也是出现同样的错误

**Comment by 11liju** [comment]
那就是一样的

**Comment by ddqp** [comment]
我的也有类似现象，不过你稍等10秒，就会变动了，简单来说，就好像有卡顿现象

**Comment by Awelling2** [comment]
我的登录都不行，一直是Login Failed: error: 5 See popped out window.

**Comment by G-Joker** [comment]
出现这个

root@vultr:/home/BaiduPCS# pcs login
User Name: 130***46880
Password:
The captcha image at /root/.pcs/captcha.gif.
Please input the captcha code: AEXQ
Login Failed: error: 5 See popped out window.

**Comment by 11liju** [comment]
我的也是一样，无法登录Login Failed: error: 5 See popped out window.

**Comment by wallena3** [comment]
下载有假死的情况，十秒左右流量才动一次，基本没法用了。应该是百度对api处理了

**Comment by G-Joker** [comment]
够呛

**Comment by GuangLightman** [comment]
同为
Login Failed: error: 5 See popped out window.

**Comment by GangZhuo** [comment]
fixed
