### ISSUE TITLE
对于api的泛滥使用，百度网盘在3.8妇女节那天已经有所行动了

### ISSUE THREAD

**Issue by Droid-MAX** [GangZhuo/BaiduPCS#151]
出现登录失败，下载文件速度上不去的，你们的账号就得当心了，据小道消息，百度网盘开始针对使用api的这些用户进行封号处理了，望所有人知悉！

**Comment by 11liju** [comment]
百度开始查了

**Comment by xdibin** [comment]
登陆返回错误码 5 ，从JS里面分析，意思要要在打开的新窗口中操作。
查看百度登陆的页面，发现在 checklogin 和 login 请求的参数里面新增了一个 dv 的变量，例如：
MDEwAAoAlgAKAroAIQAAAF00AAcCAATLy8vLCQIAMO_s8_MVFRUVFVWmpvKz_broqeS75LTnt-jcg9yszb7NutWnw5zsgOGC54_gjOiN_wgCAC3v7MzMJCQkZBhMDUMEVhdaBVoKWQlWYj1iEnMAcwRrGX0iUj5fPFkxXjJWM0EMAgAf05WVlZWo3orLhcKQ0ZzDnMyfz5Ck-6TRose1-5r3kgwCAB_TlZWVlalnM3I8eyloJXoldSZ2KR1CHWgbfgxCI04rDAIAH9OVlZWVqY_bmtSTwYDNks2dzp7B9ar1gPOW5KrLpsMMAgAf05WVlZWu0ITFi8ye35LNksKRwZ6q9arfrMm79ZT5nAcCAATLy8vLDAIAH9OVlZWVr3ElZCptP34zbDNjMGA_C1QLfg1oGlQ1WD0NAgAFy8v4KSkJAgAk09CIiE1NTU1NfrW14aDuqfu696j3p_Sk-8-Qz7rJrN6Q8Zz5CAIAIdPQu7tlZWVXKn4_cTZkJWg3aDhrO2RQD1AgQTJBNlkrTwkCABTLyCYmVlZWVlZmNTQ35-eGhsbG0w0CAAXLy-fJyQ0CAAXLy8KVlQcCAATLy8vLBgIAKMvLy11dXV9nZ2djT09PTYGBgYaVlZWWbW1tanl5eXqvr6-vr6-vr68XAgAKysthYWQAbwx5FBYCACPpnfbG6Nzp3uje79zt3u3V4dHo3-re79vj2uvY7dzl1uHX5gQCAAXKysvK_RUCAAjLy8qQJ3i2HQECAAbLysrEU-EFAgAEy8vLwRACAAHLEwIAGcve3t62wrbG_NP8jO2Drc-ux6PW-Jv0mbYIAgAJy8gSEm5ubkEHBwIABMvLy8sNAgAFy8v7o6MNAgAFy8v7oqIHAgAEy8vLywgCACHT0NfXFxcXIl4KSwVCEFEcQxxMH08QJHskUSJHNXsadxIHAgAEy8vLywcCAATLy8vL

此外，百度在 login请求中对 password 进行了加密，但是PCS的代码是没有加密的。

**Comment by 11liju** [comment]
那怎么办，又没有解决的办法

**Comment by FuGoGo** [comment]
如果获知其新增规则 可以对这个项目进行改进（应该有大佬来）

**Comment by urain39** [comment]
有没有办法在其他浏览器里提取cookie然后作为密码登录？

**Comment by xdibin** [comment]
可以参考下这个：https://github.com/qiyeboy/baidulogin

**Comment by 11liju** [comment]
但愿尽早解决吧

**Comment by CNMan** [comment]
下载貌似有规律的断断续续
![2017-03-11_133408](https://cloud.githubusercontent.com/assets/8692234/23820951/d6647272-065f-11e7-850c-4eca7b953480.png)
![2017-03-11_133551](https://cloud.githubusercontent.com/assets/8692234/23820952/d98b8be8-065f-11e7-943c-e066171dd86b.png)

**Comment by Gilbert-Wong** [comment]
还是自己组个NAS靠谱啊。。。。

**Comment by jizeguo** [comment]
10KB每秒。。开会员还是10KB每秒，非得超级会员，绝望

**Comment by qq361168780** [comment]
求大神们跟进一下这个项目

**Comment by WeihuaGu** [comment]
暂时只能导出下载链接，然后用axel了……

**Comment by jizeguo** [comment]
先手机山寨云凑活着用。。

**Comment by xdibin** [comment]
有哪位知道 login 请求中的 dv 参数是怎么生成的吗？看了一天百度登陆页面的js代码，没看到哪里生成的

**Comment by GangZhuo** [comment]
3.min.js 中，采集用户行为习惯，和历史习惯对比来判断账号是否异常登录。

bin <notifications@github.com>于2017年3月14日周二 下午8:00写道：

**Comment by giveup** [comment]
@Droid-MAX 已经被限速的是不是无解,只能放弃账号处理?

**Comment by zby1234** [comment]
试着把IE里的cookie导出替换VPS上的default.cookie登录成功了，上传到百度速度很快。下载没试过，因为直接本地客户端开会员下载的。

**Comment by 11liju** [comment]
怎么操作

**Comment by zby1234** [comment]
我是ubuntu的系统，用IE登陆了下百度账号和度盘，然后导出cookie，名字改成default.cookie，放进 /root/.pcs 里面替换掉原来的那个，然后就可以了。

**Comment by 11liju** [comment]
macOS没发现里面有default.cookie

**Comment by giveup** [comment]
@11liju pcs context,shift+command+g

**Comment by xdibin** [comment]
@GangZhuo 从chrome的的请求里面，抓了一个dv填入login请求的参数里面，服务器返回的错误是1，提示账户名不正确，但是账户名是对的。怎么解？

**Comment by WeihuaGu** [comment]
受@zby1234 启发。linux用户，使用firefox的化，firefox有个插件叫Cookies Export/import，用这个也可以方便的cookie导出来，重命名成default.cookie就好

**Comment by lich1288** [comment]
Firefox的所有Cookie存储在Profiles目录下cookies.sqlite数据库中，可以用SQLite3进行访问

**Comment by 11liju** [comment]
@giveup 具体路径是？

**Comment by G-Joker** [comment]
登录是个问题，我不想这个项目烂尾

**Comment by mayuuko** [comment]
那請問windows系統又可以如何做?

**Comment by 11liju** [comment]
@zby1234 替换了cookie，还是不行，无法登陆

**Comment by 11liju** [comment]
@zby1234 登录没有问题，但是无法下载，断断续续的

**Comment by GangZhuo** [comment]
登录问题修好了。下载断断续续的问题，先观察一段时间。

**Comment by g-joker** [comment]
加油

**Comment by XueSeason** [comment]
@GangZhuo 请问关于 dv 参数生成，有具体资料可以参阅吗？我只看到你的项目下有个 pcs_passport_dv 文件。望作者点拨下思路。

**Comment by GangZhuo** [comment]
没有，直接看代码吧，应该还是比较清晰的。可以从 print 函数看包的格式。

Jijie.Xue <notifications@github.com>于2017年3月30日周四 下午8:47写道：

**Comment by GangZhuo** [comment]
大概就是 头部|数据块|数据块... ，头部包含长度，每个数据块也包含一个数据块头部。 每个数据块使用异或加密，整个数据使用变异的 base64 加密。整个数据块的 16 位长度可以看 ppa 方法。每个数据块记录的就是用户的行为，例如移动鼠标、按键和鼠标点击等，还包含使用的浏览器名称，浏览器版本，窗口宽高等。

**Comment by GangZhuo** [comment]
逻辑全在 pcs_passport_dv 文件中

**Comment by GangZhuo** [comment]
https://github.com/GangZhuo/BaiduPCS/blob/master/pcs/pcs_passport_dv.c#L1098 开始构建的几个块是 每个 dv 必须有的数据块，passport_dv_imitate 函数中的是可变的，不同的用户可能不同。数据块的顺序是随机的，在添加数据块的时候，大概有一半的几率插入到缓存的开始处，一半的几率直接添加到结尾。其中，移动鼠标，按键，焦点事件有最大数量限制，超过就不记录了。 只记录用户名文本框的按键，不记录密码框的输入按键。

**Comment by fybmain** [comment]
是否需要搞一个页面，让pcs自动检查这个页面，在bd的api升级后我们改变这个页面的内容，来起到通知用户原有api已经不安全的作用？

**Comment by GangZhuo** [comment]
没有必要。

fyb <notifications@github.com>于2017年4月1日周六 下午4:21写道：
