### ISSUE TITLE
can not login

### ISSUE THREAD

**Issue by vitaly-zdanevich** [GangZhuo/BaiduPCS#156]
Login Failed: error: 5 See popped out window.

**Comment by derekhe** [comment]
see: 
git clone https://github.com/xdibin/BaiduPCS
cd BaiduPCS
git checkout -b httpd origin/httpd
make 
make install

Good luck

**Comment by 11liju** [comment]
@derekhe 无法clone显示fatal: destination path 'BaiduPCS' already exists and is not an empty directory.

**Comment by GangZhuo** [comment]
fixed
