### ISSUE TITLE
会有OpenWrt的版本吗 ?

### ISSUE THREAD

**Issue by pexcn** [GangZhuo/BaiduPCS#17]

**Comment by GangZhuo** [comment]
Fixed

**Comment by pexcn** [comment]
Thanks.

**Comment by pexcn** [comment]
很好~

![pcs](https://cloud.githubusercontent.com/assets/4590439/7213983/39996058-e5c6-11e4-9d16-112a217adda9.png)

**Comment by pexcn** [comment]
分享一个ramips版本的，改后缀名为ipk就能安装了

![baidupcs_0 2 0_ramips_24kec ipk](https://cloud.githubusercontent.com/assets/4590439/7213985/5b52bd0c-e5c6-11e4-8a79-34f1e1b337f0.png)

**Comment by GangZhuo** [comment]
感谢，已经添加到预编译下载列表中。
