### ISSUE TITLE
使用pcs ehco -a 时应该怎么换行

### ISSUE THREAD

**Issue by WeihuaGu** [GangZhuo/BaiduPCS#172]
我想用pcs echo -a 的内容添加在下一行而不是直接拼接在它的后面。
例如 pcs echo test 'this is a test'
然后pcs echo -a test 'this is a test for line feed'

然后 变成了 this is a testthis is a test for line feed

怎么样可以变成
this is a test
this is a test for line feed

**Comment by GangZhuo** [comment]
Windows 下 使用 "^" 符号。

![capture](https://cloud.githubusercontent.com/assets/1397462/25163410/2bfc7c10-2498-11e7-9340-084c97bd7358.PNG)

**Comment by WeihuaGu** [comment]
@GangZhuo 那linux下呢？ 我试了 pcs echo -a test "line 2"\n\r 不管用

**Comment by GangZhuo** [comment]
敲一个双引号，然后回车...，再敲关闭的双引号。我记得 linux 下 \n 应该是工作的，空时试试。

**Comment by WeihuaGu** [comment]
@GangZhuo 感谢！ 敲一个引号，再回车，再敲结束的引号是管用的。
