### ISSUE TITLE
关于文件同步问题

### ISSUE THREAD

**Issue by tenwx** [GangZhuo/BaiduPCS#176]
请教下compare功能我看到介绍是比较双边的修改时间来判断哪些需要上传和下载，那是不是意味着不支持同步删除操作？还有貌似也不支持空目录的同步？

**Comment by GangZhuo** [comment]
空目录是支持的。删除的文件会从另一边同步过来，除非两边都删除。例如，网盘中文件被删除了，那么同步时会把本地的文件上传上去；如果本地文件被删除了，那么同步时，会从网盘下载。

tenwx <notifications@github.com>于2017年4月27日周四 下午8:56写道：
