### ISSUE TITLE
希望使用合适的构建系统（CMake/Autotools）代替手写Makefile

### ISSUE THREAD

**Issue by hosiet** [GangZhuo/BaiduPCS#183]
手写Makefile不够灵活，也缺乏跨平台支持。使用合适的构建系统（CMake/Autotools）可以解决这些问题。

**Comment by GangZhuo** [comment]
CMake/Autotools 不熟悉，可以提 PR。

**Comment by hosiet** [comment]
OK 预订✓

**Comment by daoxunchen** [comment]
试试premake 或者xmake，比cmake还要简便一点
