### ISSUE TITLE
想在list 某个dir的时候没有翻页，该怎么写参数？

### ISSUE THREAD

**Issue by YuSuu** [GangZhuo/BaiduPCS#189]
我尝试翻阅了 help mannul，好像没有该选项。
请指教！

**Comment by GangZhuo** [comment]
baidupcs set --page_list_size=0

Xpec1al <notifications@github.com>于2017年5月29日周一 上午6:08写道：

**Comment by YuSuu** [comment]
@GangZhuo  thanks
刚翻阅了下。正确的命令是 `pcs set --list_page_size=xx`
然后提示里说 必须>0，
