### ISSUE TITLE
安装到make clean这一步时，提示make: *** No rule to make target 'clean'.  Stop.

### ISSUE THREAD

**Issue by FYpanda** [GangZhuo/BaiduPCS#195]
![image](https://cloud.githubusercontent.com/assets/20028752/26760457/e0b6ca94-494a-11e7-8678-0c8d7e85e061.png) 
系统：Ubuntu 16.04

**Comment by VeritasPotter** [comment]
先配置Make参数 
`./configure`
再运行
`make clean`

**Comment by linyf2008** [comment]
下载的文件中有一个叫做makefile.old。先将它重命名：(注意大小写)
`mv Makefile.old Makefile`
然后，
`make clean`
再然后就正常地走咯

**Comment by Roadchen** [comment]
`mv Makefile.old Makefile`后再`make clean` 会提示
```
Makefile:49: "Use 'make ver=debug' to build for gdb debug."
rm -f ./bin/*.o ./bin/*.so ./bin/pcs
```

**Comment by Roadchen** [comment]
`/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
depbase=`echo pcs/cJSON.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/cJSON.lo -MD -MP -MF $depbase.Tpo -c -o pcs/cJSON.lo pcs/cJSON.c &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/cJSON.lo -MD -MP -MF pcs/.deps/cJSON.Tpo -c pcs/cJSON.c  -fno-common -DPIC -o pcs/.libs/cJSON.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/cJSON.lo -MD -MP -MF pcs/.deps/cJSON.Tpo -c pcs/cJSON.c -o pcs/cJSON.o >/dev/null 2>&1
depbase=`echo pcs/pcs_fileinfo.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_fileinfo.lo -MD -MP -MF $depbase.Tpo -c -o pcs/pcs_fileinfo.lo pcs/pcs_fileinfo.c &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_fileinfo.lo -MD -MP -MF pcs/.deps/pcs_fileinfo.Tpo -c pcs/pcs_fileinfo.c  -fno-common -DPIC -o pcs/.libs/pcs_fileinfo.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_fileinfo.lo -MD -MP -MF pcs/.deps/pcs_fileinfo.Tpo -c pcs/pcs_fileinfo.c -o pcs/pcs_fileinfo.o >/dev/null 2>&1
depbase=`echo pcs/pcs_http.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_http.lo -MD -MP -MF $depbase.Tpo -c -o pcs/pcs_http.lo pcs/pcs_http.c &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_http.lo -MD -MP -MF pcs/.deps/pcs_http.Tpo -c pcs/pcs_http.c  -fno-common -DPIC -o pcs/.libs/pcs_http.o
pcs/pcs_http.c:100:9: warning: enumeration value 'HTTP_METHOD_NONE' not handled in switch [-Wswitch]
        switch(method)
               ^
1 warning generated.
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_http.lo -MD -MP -MF pcs/.deps/pcs_http.Tpo -c pcs/pcs_http.c -o pcs/pcs_http.o >/dev/null 2>&1
depbase=`echo pcs/pcs_mem.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_mem.lo -MD -MP -MF $depbase.Tpo -c -o pcs/pcs_mem.lo pcs/pcs_mem.c &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_mem.lo -MD -MP -MF pcs/.deps/pcs_mem.Tpo -c pcs/pcs_mem.c  -fno-common -DPIC -o pcs/.libs/pcs_mem.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_mem.lo -MD -MP -MF pcs/.deps/pcs_mem.Tpo -c pcs/pcs_mem.c -o pcs/pcs_mem.o >/dev/null 2>&1
depbase=`echo pcs/pcs_pan_api_resinfo.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_pan_api_resinfo.lo -MD -MP -MF $depbase.Tpo -c -o pcs/pcs_pan_api_resinfo.lo pcs/pcs_pan_api_resinfo.c &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_pan_api_resinfo.lo -MD -MP -MF pcs/.deps/pcs_pan_api_resinfo.Tpo -c pcs/pcs_pan_api_resinfo.c  -fno-common -DPIC -o pcs/.libs/pcs_pan_api_resinfo.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_pan_api_resinfo.lo -MD -MP -MF pcs/.deps/pcs_pan_api_resinfo.Tpo -c pcs/pcs_pan_api_resinfo.c -o pcs/pcs_pan_api_resinfo.o >/dev/null 2>&1
depbase=`echo pcs/pcs_slist.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_slist.lo -MD -MP -MF $depbase.Tpo -c -o pcs/pcs_slist.lo pcs/pcs_slist.c &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_slist.lo -MD -MP -MF pcs/.deps/pcs_slist.Tpo -c pcs/pcs_slist.c  -fno-common -DPIC -o pcs/.libs/pcs_slist.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_slist.lo -MD -MP -MF pcs/.deps/pcs_slist.Tpo -c pcs/pcs_slist.c -o pcs/pcs_slist.o >/dev/null 2>&1
depbase=`echo pcs/pcs_utils.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_utils.lo -MD -MP -MF $depbase.Tpo -c -o pcs/pcs_utils.lo pcs/pcs_utils.c &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_utils.lo -MD -MP -MF pcs/.deps/pcs_utils.Tpo -c pcs/pcs_utils.c  -fno-common -DPIC -o pcs/.libs/pcs_utils.o
pcs/pcs_utils.c:12:10: fatal error: 'openssl/md5.h' file not found
#include <openssl/md5.h>
         ^
1 error generated.
make[1]: *** [pcs/pcs_utils.lo] Error 1`

**Comment by Roadchen** [comment]
```
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
depbase=`echo pcs/cJSON.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/cJSON.lo -MD -MP -MF $depbase.Tpo -c -o pcs/cJSON.lo pcs/cJSON.c &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/cJSON.lo -MD -MP -MF pcs/.deps/cJSON.Tpo -c pcs/cJSON.c  -fno-common -DPIC -o pcs/.libs/cJSON.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/cJSON.lo -MD -MP -MF pcs/.deps/cJSON.Tpo -c pcs/cJSON.c -o pcs/cJSON.o >/dev/null 2>&1
depbase=`echo pcs/pcs_fileinfo.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_fileinfo.lo -MD -MP -MF $depbase.Tpo -c -o pcs/pcs_fileinfo.lo pcs/pcs_fileinfo.c &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_fileinfo.lo -MD -MP -MF pcs/.deps/pcs_fileinfo.Tpo -c pcs/pcs_fileinfo.c  -fno-common -DPIC -o pcs/.libs/pcs_fileinfo.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_fileinfo.lo -MD -MP -MF pcs/.deps/pcs_fileinfo.Tpo -c pcs/pcs_fileinfo.c -o pcs/pcs_fileinfo.o >/dev/null 2>&1
depbase=`echo pcs/pcs_http.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_http.lo -MD -MP -MF $depbase.Tpo -c -o pcs/pcs_http.lo pcs/pcs_http.c &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_http.lo -MD -MP -MF pcs/.deps/pcs_http.Tpo -c pcs/pcs_http.c  -fno-common -DPIC -o pcs/.libs/pcs_http.o
pcs/pcs_http.c:100:9: warning: enumeration value 'HTTP_METHOD_NONE' not handled in switch [-Wswitch]
        switch(method)
               ^
1 warning generated.
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_http.lo -MD -MP -MF pcs/.deps/pcs_http.Tpo -c pcs/pcs_http.c -o pcs/pcs_http.o >/dev/null 2>&1
depbase=`echo pcs/pcs_mem.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_mem.lo -MD -MP -MF $depbase.Tpo -c -o pcs/pcs_mem.lo pcs/pcs_mem.c &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_mem.lo -MD -MP -MF pcs/.deps/pcs_mem.Tpo -c pcs/pcs_mem.c  -fno-common -DPIC -o pcs/.libs/pcs_mem.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_mem.lo -MD -MP -MF pcs/.deps/pcs_mem.Tpo -c pcs/pcs_mem.c -o pcs/pcs_mem.o >/dev/null 2>&1
depbase=`echo pcs/pcs_pan_api_resinfo.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_pan_api_resinfo.lo -MD -MP -MF $depbase.Tpo -c -o pcs/pcs_pan_api_resinfo.lo pcs/pcs_pan_api_resinfo.c &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_pan_api_resinfo.lo -MD -MP -MF pcs/.deps/pcs_pan_api_resinfo.Tpo -c pcs/pcs_pan_api_resinfo.c  -fno-common -DPIC -o pcs/.libs/pcs_pan_api_resinfo.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_pan_api_resinfo.lo -MD -MP -MF pcs/.deps/pcs_pan_api_resinfo.Tpo -c pcs/pcs_pan_api_resinfo.c -o pcs/pcs_pan_api_resinfo.o >/dev/null 2>&1
depbase=`echo pcs/pcs_slist.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_slist.lo -MD -MP -MF $depbase.Tpo -c -o pcs/pcs_slist.lo pcs/pcs_slist.c &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_slist.lo -MD -MP -MF pcs/.deps/pcs_slist.Tpo -c pcs/pcs_slist.c  -fno-common -DPIC -o pcs/.libs/pcs_slist.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_slist.lo -MD -MP -MF pcs/.deps/pcs_slist.Tpo -c pcs/pcs_slist.c -o pcs/pcs_slist.o >/dev/null 2>&1
depbase=`echo pcs/pcs_utils.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
	/bin/sh ./libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I.    -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_utils.lo -MD -MP -MF $depbase.Tpo -c -o pcs/pcs_utils.lo pcs/pcs_utils.c &&\
	mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -g -Wall -I. -I./pcs -I./rb_tree -g -O2 -Qunused-arguments -pthread -MT pcs/pcs_utils.lo -MD -MP -MF pcs/.deps/pcs_utils.Tpo -c pcs/pcs_utils.c  -fno-common -DPIC -o pcs/.libs/pcs_utils.o
pcs/pcs_utils.c:12:10: fatal error: 'openssl/md5.h' file not found
#include <openssl/md5.h>
         ^
1 error generated.
make[1]: *** [pcs/pcs_utils.lo] Error 1
make: *** [all] Error 2
```

**Comment by GangZhuo** [comment]
mv Makefile.old Makefile
make clean
make
make install
