### ISSUE TITLE
怎么静默下载？

### ISSUE THREAD

**Issue by suninsky** [GangZhuo/BaiduPCS#198]
即怎么静默下载，只显示下载速度以及进度，而不跳出一大堆错误。

**Comment by GangZhuo** [comment]
试试 2>/dev/null 来忽略错误

suninsky plate <notifications@github.com>于2017年6月14日周三 下午3:44写道：

**Comment by GangZhuo** [comment]
试试 2>/dev/null 忽略错误

**Comment by suninsky** [comment]
@GangZhuo 没有用 
Download slice failed, retry delay 10 second, tid: 0x7fcab0770700. message: Failure when receiving data from the peer: 
Download slice failed, retry delay 10 second, tid: 0x7fca5eecd700. message: 406 (null)

一开始下载全屏都是这类提示，而看不到下载进度

**Comment by kcity2008** [comment]
跟我的一样，同步百度和谐掉的文件，就会出现这个，一直在retry ,不知道有没有什么办法解决。我现在就 是先把和谐掉的文件移出同步文件夹

**Comment by GangZhuo** [comment]
使用最新版
