### ISSUE TITLE
0.3版本无法加速下载

### ISSUE THREAD

**Issue by Suzune9** [GangZhuo/BaiduPCS#226]
同一个文件，同样的线程数，使用0.2.6版本可以达到1M/s左右的速度，0.3版本大概只有几十k/s，win1064位系统，小白提问可能不符合规范，可以提供更多信息。谢谢

**Comment by GangZhuo** [comment]
增加线程数量试试。我这边设置了200线程，速度还可以。不过速度还是不稳定。
