### ISSUE TITLE
下载的大文件经常损坏

### ISSUE THREAD

**Issue by xodidox** [GangZhuo/BaiduPCS#231]
下载的大文件经常损坏，特别是5G以上的文件。有些在下载过程中会提示一些slice出错重试，有些没有任何错误信息，但下载的文件MD5不对。大部分出错文件可以通过多次重新下载来解决，但都是大文件，多次下载非常耗时。我对比了出错的文件，发现其中一些错误内容是一些json错误信息（time_out之类的），PCS把错误信息当做了文件数据，很多其它错误看不出什么规律。当下载出错重试也无法恢复时，为什么不直接终止而要继续下载？这时候继续下载已经没有任何意义了。

**Comment by GangZhuo** [comment]
Timeout 应该返回错误码的，这个时候应该不会写入文件的。找个时间调试看看

**Comment by xodidox** [comment]
有些文件，多次下载始终文件损坏。我用其它软件JDownloader之类的，发现下载一部分之后（4G左右），出现连接错误，然后等待一段时间重新连接继续下载，结果文件是损坏的。多次重试，现象都一样，看起来好像文件的一部分是存在一个地方，另一部分存在其它地方，结果导致下载软件处理出错。
