### ISSUE TITLE
Error: Can't create the temp file  (For large file only - i.e. > 2GB)

### ISSUE THREAD

**Issue by gmuskie** [GangZhuo/BaiduPCS#24]
### Version info ###
pcs version
pcs v0.2.1 (API v1.1.1)pcs

### Listing for the size of /tv/jurassic.mkv (2.7GB）###
pcs list /tv/
PAGE#1
D       Size Modify Date Time    File Name
------------------------------------------------------------------------------
d          0 2015-07-13 17:09:14 /tv/Jurassic.World.2015.1080p.HDRip.KORSUB.x264.AAC2.0-RARBG
d          0 2015-07-13 17:11:50 /tv/Jurassic.World.2015.720p.HC.HDRip.X264.AC3-EVO
d          0 2015-07-11 18:35:46 /tv/taxi
- 2749372028 2015-07-13 17:16:40 /tv/jurassic.mkv
- 1807641558 2015-06-30 11:08:25 /tv/majong.mp4
------------------------------------------------------------------------------
Total: 4.24GB, File Count: 2, Directory Count: 3

### Download /tv/jurassic.mkv and get the error ### 
pcs download /tv/jurassic.mkv jurassic.mkv
Error: Can't create the temp file: jurassic.mkv.0deb2d970640a1bd8dedec8b92b7fd55.pcs_temp, maybe have no disk space.

**Comment by GangZhuo** [comment]
1. 请检查磁盘是否有足够的空间
2. 请检查运行pcs的用户对本地目录是否有写的权限

我经常下载超2GB文件，11GB多的文件也能正常下载，我用的系统是Debian。

**Comment by gmuskie** [comment]
謝謝你的回覆。你這個程序超好用。 下載速度又快。所以希望可以解決一下在我這邊的下載大檔案問題。

1.请检查磁盘是否有足够的空间
df 是這樣的. 我的下載是放到 /mnt/usb_500g。現在裡面還有 413GB 啊。

df -h
Filesystem      Size  Used Avail Use% Mounted on
rootfs           15G  7.1G  7.0G  51% /
/dev/root        15G  7.1G  7.0G  51% /
devtmpfs        214M     0  214M   0% /dev
tmpfs            44M  568K   43M   2% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs            88M     0   88M   0% /run/shm
/dev/mmcblk0p1   56M   19M   38M  34% /boot
/dev/sda1       458G   22G  413G   5% /mnt/usb_500g

2. 请检查运行pcs的用户对本地目录是否有写的权限
因為下載 <2G 檔案沒有問題，所以應該不是權限問題。

Note: 我是用樹莓派的 Raspian. 有沒有一些地方要注意呢？

**Comment by GangZhuo** [comment]
usb_500g 的文件系统是什么格式？ FAT32, ext4 ？
FAT32单文件最大允许 4 GB。

**Comment by gmuskie** [comment]
是 ext4 :

df -T
Filesystem     Type     1K-blocks     Used Available Use% Mounted on
rootfs         rootfs    15427568  7431168   7333500  51% /
/dev/root      ext4      15427568  7431168   7333500  51% /
devtmpfs       devtmpfs    218672        0    218672   0% /dev
tmpfs          tmpfs        44588      568     44020   2% /run
tmpfs          tmpfs         5120        0      5120   0% /run/lock
tmpfs          tmpfs        89160        0     89160   0% /run/shm
/dev/mmcblk0p1 vfat         57288    19208     38080  34% /boot
/dev/sda1      ext4     479913728 22739112 432773364   5% /mnt/usb_500g

**Comment by GangZhuo** [comment]
使用最新的代码编译，然后试看看...

**Comment by gmuskie** [comment]
剛剛下載最新的代码编译。現在沒有問題了。開心使用中。謝謝！

pcs download /tv/jurassic_4GB.mp4 /var/www/bt/jurassic_4GB.mp4
407.56MB/4.00GB         2.36MB/s         00:26:03
