### ISSUE TITLE
在 VS 2013 编译 64bit  报错

### ISSUE THREAD

**Issue by aeeq** [GangZhuo/BaiduPCS#25]
error LNK1112: 模块计算机类型“X86”与目标计算机类型“x64”冲突	BaiduPCS-master\pcs\argp.lib(vsnprintf.obj)	BaiduPCS_DLL

**Comment by GangZhuo** [comment]
依赖库全部都是基于 x86 编译的。或者你可以自己编译依赖库： https://github.com/peters/curl-for-windows
