### ISSUE TITLE
BaiduPCS下载大文件经常损坏，但用BaiduPCS_NET却文件完整

### ISSUE THREAD

**Issue by xodidox** [GangZhuo/BaiduPCS#251]
测试了5个大文件（均超过10G），无论是用pcs/aria2/jdownloader，发现其中一个文件始下载下来好几次，始终MD5不匹配，但是都是同一个错误的MD5，然后用BaiduPCS_NET下载下来却是正确的MD5。其它几个文件错误没什么规律，但用BaiduPCS_NET下载MD5都能匹配。BaiduPCS和BaiduPCS_NET除了GUI，还有其它区别？看起来好像是它们在处理下载出错或者服务器无连接时的处理方法不一样，因为下载这些文件的时候，都遇到了中途下载速度是0的情况。

**Comment by derekhe** [comment]
+1

**Comment by aries1998** [comment]
我这边某些大文件也这样, 能不能在配置文件pcs_context或者命令行加个强制md5校验的选项, 有问题就重新下, 虽然不那么优雅
