### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by fox0001** [GangZhuo/BaiduPCS#27]
1）树莓派raspbian下，用户pi登录网盘，并设置定时任务（crontab -e）来自动同步，但是pcs命令都执行失败。这个该如何解决？

2）pcs search查找不到结果，执行echo $?显示0。应该参考其它linux命令，查找不到结果时返回1。

3）pcs upload -f /local/a.txt /remote/a.txt 如果网盘不存在/remote/a.txt，会报错。应该改为程序自动判断网盘是否已存在该问题，若存在，则自动覆盖。既然已经加上-f，表示需要强制复制，为什么还要提示错误？

**Comment by GangZhuo** [comment]
* 能否贴出日志。

例如：

crontab配置如下:

    */1 * * * * /usr/local/bin/pcs quota >>/tmp/pcs.log 2>&1

执行如下命令输出日志：
    cat /tmp/pcs.log


* 修改好了。 https://github.com/GangZhuo/BaiduPCS/commit/ad36b7d9a0460c157d16337b4fa421baeb01b9b9

* 未能重现，无论是目录不存在还是文件不存在，都能正常上传。

**Comment by fox0001** [comment]
感谢这么这么快速的回复！
1）你的配置没问题。那么，应该是我的脚本问题，我再检查下吧。

2）更新代码并编译后，问题已解决。非常感谢！

3）确实是没问题。应该是我的问题。可能有另一个进程在写入文件，所以导致该文件不能上传。
