### ISSUE TITLE
无法保存验证码图片

### ISSUE THREAD

**Issue by starP-W** [GangZhuo/BaiduPCS#277]
在debian8 及9进行了编译，且已经将验证码保存路径设置为可写，
但无论是用新方法还是旧方法编译后进行登陆都显示
Can't save the captcha image to xxx(路径).

是否是我哪一步编译出现了问题，还是需要安装其它的依赖？

**Comment by assassinwrz** [comment]
尝试检查一下写入目录的权限？

**Comment by arhaha** [comment]
这个验证码保存路径的要求是一个文件，不能是一个目录。

**Comment by starP-W** [comment]
感谢，问题已解决，原来需要的是文件路径而不是目录路径
