### ISSUE TITLE
我想问一下 ，大神是怎么分析出网盘的接口的，用chrome debug?

### ISSUE THREAD

**Issue by fecloud** [GangZhuo/BaiduPCS#28]

**Comment by GangZhuo** [comment]
是的

fecloud <notifications@github.com>于2015年9月26日周六 下午10:15写道：

**Comment by fecloud** [comment]
那些秒传，分片上传的呢，chrome不支持分片上传和秒传吧，ps:中秋节快乐

**Comment by GangZhuo** [comment]
结合官方api，分析抓包。

fecloud <notifications@github.com>于2015年9月27日周日 下午5:51写道：

**Comment by fecloud** [comment]
官方api？android 、ios、还是？

**Comment by GangZhuo** [comment]
http://developer.baidu.com/wiki/index.php?title=docs/pcs/rest/file_data_apis_list

**Comment by GangZhuo** [comment]
这个地址看起来好像被官方隐藏了，直接从开发者中心的首页没有找到进入的链接。

**Comment by wojiaojiao** [comment]
用火狐debug可以吗？

**Comment by wojiaojiao** [comment]
什么叫抓包呀？
