### ISSUE TITLE
Openwrt SDK无法编译

### ISSUE THREAD

**Issue by ljkgpxs** [GangZhuo/BaiduPCS#31]
按步骤执行之后会
/home/ljkgpxs/src/openwrt/trunk/sdk/OpenWrt-SDK-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/scripts/download.pl "/home/ljkgpxs/src/openwrt/trunk/sdk/OpenWrt-SDK-ramips-mt7620_gcc-4.8-linaro_uClibc-0.9.33.2.Linux-x86_64/dl" "0.2.0.tar.gz" "unknown" "https://github.com/GangZhuo/BaiduPCS/archive"
然后一直尝试下载0.2.0.tar.gz，直到失败。。。

**Comment by GangZhuo** [comment]
via https://github.com/GangZhuo/BaiduPCS/commit/170f65ae8523c2b264341b88417a381a8616d274
