### ISSUE TITLE
交叉编译  无法解析主机名

### ISSUE THREAD

**Issue by hyh7171987717** [GangZhuo/BaiduPCS#32]
本地编译能正确运行，但是交叉编译（arm-none-linux-gnueabi-gcc）到Android，运行
出现错误：couldn't resolve host name :http://pan.baidu.com/disk/home（网络通畅）
这是什么原因··

**Comment by hyh7171987717** [comment]
这是登录时的错误

**Comment by GangZhuo** [comment]
这是 libcurl 的错误，请自行搜索。

**Comment by hyh7171987717** [comment]
把主机名改成IP地址解决了不能解析的问题，但是又出现
login failed:invalid token. token:the fisrt two args should be string type:0.1!

**Comment by GangZhuo** [comment]
http://comments.gmane.org/gmane.comp.web.curl.library/40133
http://piggyq.com/pen/curl-fails-to-connect-to-the-internet-in-android.html

看看上边两个地址是否能解决你的问题？

**Comment by hyh7171987717** [comment]
关于token的问题这个链接有说：
http://zhidao.baidu.com/question/1445603665871001140
不知道对不对

**Comment by hyh7171987717** [comment]
把主机名换成IP地址，本地编译也会出现
login failed:invalid token. token:the fisrt two args should be string type:0.1!
按照上面2个网址给出的方案，交叉编译动态都会出现上述问题。
这估计是编译器的问题了·
换Google的编译器试试..............
