### ISSUE TITLE
Entware-ng工具链无适用makefile

### ISSUE THREAD

**Issue by cmheia** [GangZhuo/BaiduPCS#37]
好吧，我另写了个[mk](https://github.com/cmheia/my-entware-packages/tree/master/utils/baidupcs)，搞定了。
Tomato的兄弟们，你们也可以用上这款软件了。
尽管目前只编译了mipsel版。
传送门：[Entware-ng](https://github.com/Entware-ng/Entware-ng/wiki)

**Comment by ryzhovau** [comment]
Done. Please, provide a feedback.
