### ISSUE TITLE
Login Failed

### ISSUE THREAD

**Issue by gmuskie** [GangZhuo/BaiduPCS#38]
你好！

今天下載了最新的 source code 去編譯。之後執行:
pcs login --username=myUsername --password=myPassword
就出現了：
Login Failed: 

在百度盘可以看到是曾經有登入的：
15:12	香港香港	203.80.*.*	Chrome 35.0	邮箱名登录	百度云
15:09	香港香港	203.80.*.*	Chrome 35.0	邮箱名登录	百度云
15:07	香港香港	203.80.*.*	Chrome 35.0	邮箱名登录	百度云

有其它地方要注意嗎？

**Comment by GangZhuo** [comment]
重现了这个错误，等待修复吧

**Comment by 20015jjw** [comment]
LA和日本都无法登陆 网页登陆正常

**Comment by GangZhuo** [comment]
Fixed

**Comment by gmuskie** [comment]
Thanks a lot!
