### ISSUE TITLE
Repeated error, getting right after restart uploading mission

### ISSUE THREAD

**Issue by haodong** [GangZhuo/BaiduPCS#42]
The error is like this,

> Upload slice failed, retry delay 10 second, tid: 0x7f1c56fd7700. message: 408 {"error_code":31233, "error_msg":"read request body timeout"}

and this,

> Error: Can't create download thread.

**Comment by GangZhuo** [comment]
什么运行环境？

**Comment by haodong** [comment]
@GangZhuo sorry 忘记贴了
```
> export
HOME=/root
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LESS=-R
LOGNAME=root
LSCOLORS=Gxfxcxdxbxegedabagacad
MAIL=/var/mail/root
PAGER=less
PATH=/usr/local/ssl/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11
SHELL=/usr/bin/bash
SSH_CLIENT='...'
SSH_CONNECTION='...'
SSH_TTY=/dev/pts/0
TERM=xterm-256color
USER=root
ZSH=/root/.oh-my-zsh
nginxConf=/etc/nginx/nginx.conf
>
> cat /proc/version
Linux version 2.6.32-042stab108.2 (root@kbuild-rh6-x64) (gcc version 4.4.6 20120305 (Red Hat 4.4.6-4) (GCC) ) #1 SMP Tue May 12 18:07:50 MSK 2015
>
> lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 7.9 (wheezy)
Release:	7.9
Codename:	wheezy
>
> uname -a
Linux BWG 2.6.32-042stab108.2 #1 SMP Tue May 12 18:07:50 MSK 2015 x86_64 GNU/Linux
```

BTW,在传输一个较大文件（几百兆+）时没有这种错误，而在批量传输多个较小文件（几十兆+）时该错误经常会发生。

**Comment by haodong** [comment]
PS: ...and this error (usually only once per file):
`Upload slice failed, retry delay 10 second, tid: 0x7f7211fef700. message: Timeout was reached: http://c.pcs.baidu.com/rest/2.0/pcs/file?method=upload&type=tmpfile&app_id=...[ ok ]...file`

**Comment by haodong** [comment]
@GangZhuo 今天发现一个可能是造成这个error的原因，文件名较长，而且包含空格。
但是，我是用的`pcs synch`命令，后来单独用`pcs upload`改了一个简单的名字就一次成功。
