### ISSUE TITLE
网络状况不好，延迟太高，可不可以修改延迟

### ISSUE THREAD

**Issue by haaha123123123** [GangZhuo/BaiduPCS#43]
报告错误：
Error: Timeout was reached: http://pan.baidu.com/disk/home

**Comment by GangZhuo** [comment]
原本的设定是当速度持续1分钟小于10K/S时，认为是连接超时，见 https://github.com/GangZhuo/BaiduPCS/blob/master/pcs/pcs_http.c#L456

**Comment by GangZhuo** [comment]
修改为持续1分钟小于1KB/S时，认为连接超时。见 https://github.com/GangZhuo/BaiduPCS/commit/3d3af8307c79243fa46423de51c36a664c0a4032

**Comment by BlackHole1** [comment]
这里，也出现这样的问题。ping pan.baidu.com可以ping通，但是一登录就显示
`Error: Timeout was reached: http://pan.baidu.com/disk/home`
网速8M/S
