### ISSUE TITLE
cgi-bin

### ISSUE THREAD

**Issue by leenchan** [GangZhuo/BaiduPCS#46]
＃OpenWRT

/www/cgi/pcs
文件内容：
#!/bin/sh
echo "Content-type: text/html"
echo ""
set|while read LINE
do
	echo $LINE"<br>"
done
pcs help
----------------------------------------------------------------------------------------------------------------
pcs(/usr/bin/pcs) help
任何参数都没有输出，用ssh（root）操作一切正常

set 输出的变量
CONTENT_LENGTH=''
CONTENT_TYPE=''
DOCUMENT_ROOT='/www'
GATEWAY_INTERFACE='CGI/1.1'
HOSTNAME='OpenWrt'
HTTP_ACCEPT='text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'
HTTP_ACCEPT_CHARSET=''
HTTP_ACCEPT_ENCODING='gzip, deflate, '
HTTP_ACCEPT_LANGUAGE='en-US,en;q=0.8'
HTTP_AUTHORIZATION=''
HTTP_CONNECTION='keep-alive'
HTTP_COOKIE='PHPSESSID=8e2e41e7681e318af90f29b5b33b8674'
HTTP_HOST='192.168.1.1'
HTTP_REFERER=''
HTTP_USER_AGENT='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36'
HTTP_X_HTTP_METHOD_OVERRIDE=''
IFS='
'
OPTIND='1'
PATH='/sbin:/usr/sbin:/bin:/usr/bin'
PPID='2692'
PS1='w $ '
PS2='> '
PS4='+ '
PWD='/www'
QUERY_STRING=''
REDIRECT_STATUS='200'
REMOTE_ADDR='192.168.1.1'
REMOTE_HOST='192.168.1.1'
REMOTE_PORT='47433'
REQUEST_METHOD='GET'
REQUEST_URI='/cgi-bin/pcs'
SCRIPT_FILENAME='/www/cgi-bin/pcs'
SCRIPT_NAME='/cgi-bin/pcs'
SERVER_ADDR='192.168.1.1'
SERVER_NAME='192.168.1.1'
SERVER_PORT='80'
SERVER_PROTOCOL='HTTP/1.1'
SERVER_SOFTWARE='uhttpd'
SHLVL='1'

请问有解吗？

**Comment by GangZhuo** [comment]
我不懂 cgi-bin，自行搜索吧
