### ISSUE TITLE
百度开发者中心不再提供个人云存储(PCS)相关链接和服务,

### ISSUE THREAD

**Issue by ziyouren29** [GangZhuo/BaiduPCS#47]
百度开发者中心不再提供个人云存储(PCS)相关链接和服务,这个还可以继续使用吗？ 后期维护是不是会麻烦，会修改很多url地址

**Comment by wnpllrzodiac** [comment]
“个人云存储(PCS)”：不再支持新用户接入，老用户可继续使用；9月8日起，百度开发者中心不再提供个人云存储(PCS)相关链接和服务。

用一天算一天吧。不过 用电视盒子来看网盘的电视电影挺方便的。

**Comment by GangZhuo** [comment]
这个软件没有基于PCS的API，而是分析网盘网站得到的，应该和PCS是否关闭没有关系。

**Comment by wojiaojiao** [comment]
好厉害呀？你是怎样分析的，能教教我吗？

**Comment by wojiaojiao** [comment]
我想用qt开发，把本地的文件自动上传到百度云盘，怎么做

**Comment by wojiaojiao** [comment]
我还想弄360网盘的呢，还有其他网盘的，能教教我怎么分析网站吗？

**Comment by wojiaojiao** [comment]
windows平台下可以用吗？开发工具是qt的话怎么弄？

**Comment by wnpllrzodiac** [comment]
分析 的话，用 fiddler之类的工具就可以，抓http的请求。
感觉 youku tudou等的分析抓包，要更复杂些。
主要 把BDUSS获取到。模拟baidu的登陆。
