### ISSUE TITLE
文件上传限速

### ISSUE THREAD

**Issue by oneym** [GangZhuo/BaiduPCS#49]
作者你好，请问有没有上传文件限制速度的选项，我看到了有下载的限速，但是没有找到。能不能支持一下上传限速（ubuntu版本）

**Comment by GangZhuo** [comment]
没有上传限速的。将来会考虑加入。

**Comment by oneym** [comment]
感谢作者的关注，谢谢。做备份的时候，上传带宽基本上被全部占用了在上传大文件时

**Comment by GangZhuo** [comment]
Fixed via https://github.com/GangZhuo/BaiduPCS/commit/3ce5372e4f0e898f79e160984799e71a313428b8
