### ISSUE TITLE
Can't get the file size.

### ISSUE THREAD

**Issue by oneym** [GangZhuo/BaiduPCS#50]
作者你好，我在同步文件到本地时，出现了【Can't get the file size.】错误。百度云上面对应的文件大小是0B，通过火狐浏览器是可以下载文件的。麻烦关注下

**Comment by GangZhuo** [comment]
Fixed via https://github.com/GangZhuo/BaiduPCS/commit/7da59843b5bbce4989e756624ecc0f4e9339218c

**Comment by oneym** [comment]
thanks
