### ISSUE TITLE
登陆正确 但是提示失败

### ISSUE THREAD

**Issue by wangpc** [GangZhuo/BaiduPCS#51]
```
➜  playground pcs login
User Name: mask_mask
Password: 
Login Failed: Success
```

* 登录失败 
* 其实用户名密码正确
* 怀疑是百度passport的返回码改了 后面的Success应该是表示登陆成功, 但是代码改了

**Comment by levinxu** [comment]
我也是报一样的错误，显示Login Failed: Success，
⇒ pcs ls
You are not logon or your session is time out. You can login by 'login' command.

**Comment by qiangv** [comment]
I have the same question, did you resolve it?

**Comment by haodong** [comment]
save
