### ISSUE TITLE
百度云登录失败

### ISSUE THREAD

**Issue by soso8531337** [GangZhuo/BaiduPCS#52]
Login Failed: Can't parse the response as object. Response: bd__cbs__pwxtn7({"errInfo":{ "no": "0" }, "data": { "rememberedUserName" : "", "codeString" : "", "token" : "219c1e732b1f961a2512f4f6c53d899c", "cookie" : "1", "usernametype":"", "spLogin" : "rate", "disable":"", "loginrecord":{ 'email':[ ], 'phone':[ ] } }}

**Comment by soso8531337** [comment]
http://passport.baidu.com/v2/api/?getapi&tpl=netdisk&apiver=v3&tt=1460947659&class=login&logintype=basicLogin&callback=bd__cbs__pwxtn7   这样返回的json里面返回的是单引号，   你们的解析都应该有问题的啊

**Comment by liangzhdp** [comment]
也是Login Failed啊，呜呜，

**Comment by fox0001** [comment]
Login Failed: Success

**Comment by GangZhuo** [comment]
尝试一下最新的代码。

@soso8531337 cJSON 是支持单引号的，而且我这边测试了一下，确实能正常解析。

**Comment by GangZhuo** [comment]
@liangzhdp @fox0001 现在应该能登录了，见 https://github.com/GangZhuo/BaiduPCS/issues/51 https://github.com/GangZhuo/BaiduPCS/issues/53

**Comment by liangzhdp** [comment]
非常感谢，更新后可以了。

**Comment by qiangv** [comment]
pcs login 后提示：
Error: Can't read the context file (/Users/qiangv/.pcs/pcs.context).
User Name: testtest12345@qq.com
Password:
Login Success. UID: testt***45@qq.com
Error: Can't open the file: /Users/qiangv/.pcs/pcs.context
但是：
qiangvdeMacBook-Pro:bin qiangv$ ./pcs who
Error: Can't read the context file (/Users/qiangv/.pcs/pcs.context).
You are not logon or your session is time out. You can login by 'login' command.
Error: Can't open the file: /Users/qiangv/.pcs/pcs.context

这个是pcs.context有关系么？pcs.context.size==0

**Comment by fox0001** [comment]
非常感谢，树莓派又可以继续下载了～
