### ISSUE TITLE
ls命令时自动转换文件的大小

### ISSUE THREAD

**Issue by fanghuan** [GangZhuo/BaiduPCS#54]
pcs ls  输出格式是这样的
**1044374762 2016-04-26 09:45:41 /video/marvel.75.years-from.pulp.to.pop.720p.hdtv.x264-bajskorv.mkv**
文件大小（1044374762）是以 byte 为单位，阅读起来很不方便，希望能根据大小调整为 Kb,Mb等单位

**Comment by celeron533** [comment]
但是这样显示更精确。。。有时候核对一些文件的时候，大小很重要。
真若是要自动单位的话，新加个列可能更好
