### ISSUE TITLE
无法登陆或获取用户信息？

### ISSUE THREAD

**Issue by ACGunion** [GangZhuo/BaiduPCS#55]
现在在登录时可以获取到验证码，但是输入完成后无反应。也无法获取已经登录账户的信息（pcs who命令）

**Comment by bbscool** [comment]
百度云home页面有变化。 
可参照本人的fork，commit# ec6cf33

**Comment by gggin** [comment]
why not a PR?

**Comment by ACGunion** [comment]
稍后测试。感谢您。

**Comment by bbscool** [comment]
@gggin pull requested #56
