### ISSUE TITLE
怎么已经毫无反应了？

### ISSUE THREAD

**Issue by liangzhdp** [GangZhuo/BaiduPCS#57]
pcs who ，pcs login什么的，都是完全没输出了，这是怎么啦，
git pull亦提示是最新版本，大家的都怎么了？

**Comment by ljkgpxs** [comment]
百度改接口了，已经有人修改了，查看其他的Issues

**Comment by liangzhdp** [comment]
楼上的，能否说下怎么update其他人修改了的？

**Comment by ljkgpxs** [comment]
https://github.com/bbscool/BaiduPCS.git ，同样的项目fork出来的，重新clone一下就好了

**Comment by cnzhangquan** [comment]
https://github.com/GangZhuo/BaiduPCS/pull/56

**Comment by liangzhdp** [comment]
谢谢楼上两位。
