### ISSUE TITLE
OpenWRT编译版无法安装

### ISSUE THREAD

**Issue by dukedhx** [GangZhuo/BaiduPCS#59]
*#* ipkg install BaiduPCS_0.2.0_x86.ipk 
Clearing state_want and state_flag for pkg=BaiduPCS (arch_priority=0 flag=16 want=2)
Nothing to be done
An error ocurred, return value: 4.
Collected errors:
Cannot find package BaiduPCS.
Check the spelling or perhaps run 'ipkg update'

**Comment by GangZhuo** [comment]
需要自行编译.
