### ISSUE TITLE
应对无法登陆的紧急处理方法？

### ISSUE THREAD

**Issue by celeron533** [GangZhuo/BaiduPCS#62]
场景：
百度再次更改了了UI，导致本pcs无法识别，群众很着急。

能否让本程序直接接受外部传入的BDUSS，以此为凭据，进行日常上传下载操作？

```pcs set --BDUSS AAAAAAAAAAAAA...AAAAA```

**Comment by GangZhuo** [comment]
这个保存到 cookie 文件中应该就可以了，cookie 文件在用户目录的 .pcs 目录中。[未测试，你可以试一下]

Allen Zhu <notifications@github.com>于2016年6月17日周五 上午11:19写道：

**Comment by celeron533** [comment]
> 这个保存到 cookie 文件中应该就可以了，cookie 文件在用户目录的 .pcs 目录中。[未测试，你可以试一下]

刚才测了一下，在目前`pcs_isLogin()`架构下，光有`BDUSS`还不够，还需要在`default.cookie`文件下补充PTOKEN才能绕过去

**Comment by starzou** [comment]
You are not logon or your session is time out. You can login by 'login' command.

没有效果哦

**Comment by celeron533** [comment]
@starzou ，试一下删除default.cookies里的其他内容后仅保留那两行

**Comment by GangZhuo** [comment]
最简单的方法是本地登录，然后通过 scp 命令把 default.cookie 复制到服务器上。

**Comment by tetsaicn** [comment]
没有PTOKEN怎么破，editthis输出的放进去还提示要login
