### ISSUE TITLE
能指定下载的线程数吗？

### ISSUE THREAD

**Issue by sbw983** [GangZhuo/BaiduPCS#63]
RT

买了会员，在windows下下行能达到满速8m多，但是用pcs单线程只能500k左右，能否增加线程提高速度？谢谢

**Comment by GangZhuo** [comment]
https://github.com/GangZhuo/BaiduPCS#设置上下文

sbw983 <notifications@github.com>于2016年6月17日周五 下午6:51写道：

**Comment by sbw983** [comment]
谢谢啦，不好意思，就光看了download命令的参数，没看设置的说明
