### ISSUE TITLE
不能登录

### ISSUE THREAD

**Issue by soso8531337** [GangZhuo/BaiduPCS#65]
![qq 20160624165243](https://cloud.githubusercontent.com/assets/3643374/16333131/33efb1c8-3a2c-11e6-90d4-73c67e99d9ff.png)

**Comment by CNMan** [comment]
![2016-06-27_113826](https://cloud.githubusercontent.com/assets/8692234/16367955/b7fbf87e-3c5b-11e6-94e8-8d1894e38b1e.png)
WIN上也登陆不了，输入验证码就卡住不动了

**Comment by GangZhuo** [comment]
尝试最新版。
