### ISSUE TITLE
可以实现分享文件的接口？

### ISSUE THREAD

**Issue by starzou** [GangZhuo/BaiduPCS#69]

**Comment by SunRain** [comment]
分享借口的url为http://pan.baidu.com/share/set?
        ("channel", "chunlei")
        ("clienttype", "0")
        ("web", "1")
        ("app_id", "250528")  //去掉appid也可以实现分享，暂时不知道appid从何而来， 当前本机测试为250528
        ("bdstoken", "")
//        ("logid", "") 去掉此参数
，然后post表单数据为
        ("fid_list", "[]"); // file or dir object fs_id
        ("schannel", "0");
        ("channel_list", "[]"); //保留为空

**Comment by starzou** [comment]
我抓包调试了一下

Request URL

```
https://pan.baidu.com/share/set
```

Query String Parameters 

```
channel:chunlei
clienttype:0
web:1
channel:chunlei
web:1
app_id:250528
bdstoken:***
logid:***
clienttype:0
```

Form Data

```
fid_list:[968569568262118]
schannel:4
channel_list:[]
pwd:qsq9
```

表示C好久没写过了，不知仁兄 @SunRain，@GangZhuo  可以发一个 pull request

**Comment by bbscool** [comment]
可以参考我的fork

**Comment by GangZhuo** [comment]
@bbscool  Can you create a pull request?

**Comment by celeron533** [comment]
这个看上去不像是pcs的接口啊
个人觉得分享之类的使用浏览器来完成就行了。我使用PCS命令行主要是用来在VPS和自己的机器上交换文件，因为上海电信的出国速度太慢，大文件只能使用百度网盘中转，同时尽量避免被GFW流控的可能性，泪~

**Comment by GangZhuo** [comment]
不计划实现这个功能了。
