### ISSUE TITLE
求最新windows预编译版

### ISSUE THREAD

**Issue by CNMan** [GangZhuo/BaiduPCS#72]
![2016-06-27_113826](https://cloud.githubusercontent.com/assets/8692234/16367955/b7fbf87e-3c5b-11e6-94e8-8d1894e38b1e.png)
0.2.4输入验证码就卡住不动了
@GangZhuo 
谢谢:)

**Comment by GangZhuo** [comment]
See https://github.com/GangZhuo/BaiduPCS/releases

**Comment by CNMan** [comment]
![2016-08-15_144504](https://cloud.githubusercontent.com/assets/8692234/17657556/f91fe5f6-62f6-11e6-9d2d-dc4604b7041d.png)
没问题了
