### ISSUE TITLE
pcs下载时好像被限速了

### ISSUE THREAD

**Issue by BlackHole1** [GangZhuo/BaiduPCS#74]
其他下载速度是2M/s，使用PCS下载时是512KB。

**Comment by GangZhuo** [comment]
增加下载线程数试试

Black-Hole <notifications@github.com>于2016年8月28日周日 下午6:49写道：

**Comment by BlackHole1** [comment]
好的，关于“断点下载”，REMADE里没有提到，是像下面这样么？
`pcs download "1.mkv" "情书.mkv"`
`ctrl+c关闭下载`
`pcs download "1.mkv" "情书.mkv"`

下载的时候ctrl+c关闭，然后再次输入pcs就可以继续下载了？

**Comment by GangZhuo** [comment]
对

Black-Hole <notifications@github.com>于2016年8月28日周日 下午10:29写道：

**Comment by BlackHole1** [comment]
问题解决了，谢谢。现在线程改为40。会出现Download slice failed, retry delay 10 second, tid: 0x7f9574ff9700. message: Timeout was reached: http://c.pcs.baidu.com/rest/2.0/pcs/file?method=download&app_id=250528&path=%2FLove.Letter.1995.BluRay.1080p.DTS.3Audio.x264-CHD%2F1.mkv错误，不过程序会自动连接，没有什么问题。下载速度也提上去了。十分感谢
