### ISSUE TITLE
为什么一直是登录失败呢？

### ISSUE THREAD

**Issue by mackentan** [GangZhuo/BaiduPCS#75]

**Comment by GangZhuo** [comment]
最新版也不行吗？

macken <notifications@github.com>于2016年9月2日周五 上午11:48写道：

**Comment by mackentan** [comment]
是的，在不需要输入验证码的时候登录时，可以登录成功，需要验证码的时候登录就登录失败。

**Comment by GangZhuo** [comment]
应该是百度检查到帐号可能存在安全风险，需要通过手机验证码来验证一次，在外地登陆的时候可能会出现这个问题，通过 PC 打开网盘并验证一次后应该就可以了。程序目前不支持手机验证，所以仅提示 "Try again"了。

**Comment by tbfly** [comment]
120021 这种时候似乎提示这个错误。

**Comment by GangZhuo** [comment]
对，这个错误号，表示需要进行安全认证。网页上表现为弹出一个窗口让选择认证方法，并输入认证码。

Lu Zhihe <notifications@github.com>于2016年9月7日周三 上午11:19写道：
