### ISSUE TITLE
一直关心的问题，这个功能会不会被百度

### ISSUE THREAD

**Issue by advancer46** [GangZhuo/BaiduPCS#76]
最近想使用百度的PCS功能，结果PCS api权限老是申请不下来，走了一些旁门左道也没成功。
然后有人指引到这里来了。
看了一下wiki ，貌似这个原理是 模拟网页登陆到百度云盘，然后调用百度云盘的网页接口。
有一个问题，**这个程序会不会被存在稳定性问题，比如 哪天百度 在登陆的时候 增加了 其他高级验证，或者在调用接口的时候增加某些限制，那么程序还能正常使用么？**
或者另外的一种乐观的观点，这个程序是介于百度云盘和用户之间的，**只要百度开放网页登陆和网页调用api的功能，这个程序就可以正常使用。**
这些疑惑，希望有人点拨一下。

**Comment by GangZhuo** [comment]
确实如你所说，网盘网页的升级或改动可能会导致程序不可用。

advancer46 <notifications@github.com>于2016年9月4日周日 上午9:40写道：

**Comment by advancer46** [comment]
github没有站内信，所以写在这里了。
昨晚在看到你的这个项目之前，我也在看网盘网页版，准备模拟登陆，调用它的api。
后来就找到这里，GangZhuo ， 感谢你已经完成了大部分功能了。
但是离我真正想要的还有点距离。
我想在你客户端工具pcs的基础上，将里面的api封装成webservice , 给广大web开发者在程序中调用。
其实就是 pcs 替代版

**Comment by GangZhuo** [comment]
OK, 你可以自由的使用和参考这里的代码，无论用于何目的。

advancer46 <notifications@github.com>于2016年9月4日周日 下午12:17写道：
