### ISSUE TITLE
工程是否能支持生成Xcode工程项目

### ISSUE THREAD

**Issue by liufsd** [GangZhuo/BaiduPCS#77]
就像https://github.com/google/protobuf 类似这样的一个脚本生成不同平台的工程~ 
对这个领域不了解~最近想学习一下~

**Comment by GangZhuo** [comment]
通过 cmake 应该可以，不过我不会 cmake。

**Comment by liufsd** [comment]
我刚看了下cmake 确实可以的 http://stackoverflow.com/questions/1114140/is-it-possible-to-automatically-generate-xcode-projects

**Comment by liufsd** [comment]
还有一个小问题就是你做这个程序，有参考文档之类的么？

**Comment by GangZhuo** [comment]
见 https://github.com/GangZhuo/BaiduPCS/issues/28

**Comment by liufsd** [comment]
oh~ 这个不是我关心的问题~ 我的问题更想知道的是 如何实现类似的终端程序的~ 开发这种终端程序的参考文档

**Comment by liufsd** [comment]
比如我想自己实现一个简单的登录程序
login ~~~
然后显示一个数据之类的~
有开发文档么？
这个领域我没有涉猎过~ 
所以比较好奇

**Comment by GangZhuo** [comment]
这个要你自己搜索了。

**Comment by liufsd** [comment]
没有涉猎过这个领域，可以给一些参考的文档之类么？

**Comment by GangZhuo** [comment]
我也没有什么参考文档。

**Comment by GangZhuo** [comment]
你要的是这个？ https://www.gnu.org/prep/standards/standards.html

**Comment by GangZhuo** [comment]
或者  https://www.gnu.org/software/libc/manual/html_node/Argument-Syntax.html#Argument-Syntax

**Comment by liufsd** [comment]
非常感谢~ 我先看看~
