### ISSUE TITLE
命令行没法输入新的中文验证码

### ISSUE THREAD

**Issue by qingmo** [GangZhuo/BaiduPCS#78]
命令行没法输入新的中文验证码

**Comment by qingmo** [comment]
分别比较了一下web登陆接口与app登陆接口，发现web类的所有验证码都改为了中文，但是官方app的验证码还是纯英文/数字的形式。应该是针对性的进行了调整。

**Comment by GangZhuo** [comment]
我这边还未观察到有中文验证码。即使是中文验证码，命令行应该也是可以输入的。

**Comment by qingmo** [comment]
输入是可以，但是没法通过验证，命令行和界面工具我都尝试过

**Comment by qingmo** [comment]
稍后我先自己看看，然后截图出来

**Comment by ljkgpxs** [comment]
输错几次验证码之后，就会出现中文验证码了

**Comment by celeron533** [comment]
#62 试一试？

**Comment by celeron533** [comment]
今天假设了一台ubuntu虚拟机进行了测试，成功使用中文验证码直接登陆（非ssh）
猜测 @qingmo 使用SSH登陆，然后非Unicode编码的缘故？

（由于虚拟机没有中文环境，我直接在宿主机打了中文然后`ctrl-c` `ctrl-v`送进了浏览器地址栏，然后中转到terminal）
![image](https://cloud.githubusercontent.com/assets/3608762/19074901/1a4014e0-8a75-11e6-8086-755efac98ce6.png)

**Comment by qingmo** [comment]
@celeron533 我在三台机器上都尝试过登录，ssh远程树莓派linux， mac本地， windows本地，在这个问题提出的时候，第一次登陆就会要求输入中文，并且我尝试过windows的客户端（BaiduPCS .net包装的那个）也是输入中文没法通过验证。

**Comment by celeron533** [comment]
@qingmo
难道说你这边已经被要求短信验证了么？

**Comment by GangZhuo** [comment]
See https://github.com/GangZhuo/BaiduPCS/issues/80#issuecomment-254581331
