### ISSUE TITLE
疑似无法登陆

### ISSUE THREAD

**Issue by ACGunion** [GangZhuo/BaiduPCS#79]
再输入正确的密码和验证码时无法登陆成功，提示Login Failed: Try again。若输入错误会提示输入错误。

**Comment by GangZhuo** [comment]
看 https://github.com/GangZhuo/BaiduPCS/issues/75 ，是否是相同原因导致的？

**Comment by starzou** [comment]
这个问题什么时候可以修复？

**Comment by GangZhuo** [comment]
能否测试一下最新代码，我这边不需要短信验证了，没有办法测试。

**Comment by starzou** [comment]
登录
> root@Server:~# pcs login --username=myname --password=******
The captcha image at /var/www/html/captcha.gif.
Please input the captcha code: 趁着
Login Success. UID: myname

上传

> root@Server:~# pcs u ./1476931216.file 1476931216.file
98.81MB/1.28GB  15.20MB/s         00:02:12 
Upload ./1476931216.file to /1476931216.file Success.  
  
  
经测试最新版可用。
要求短信验证的问题，可通过官方登录解除后，再用pcs登录。
  
"captchafile":	"/root/.pcs/captcha.gif",
提点建议，默认的验证码储存路径是否可以改为/var/www/html/captcha.gif，方便浏览器查看。

**Comment by GangZhuo** [comment]
看 https://github.com/GangZhuo/BaiduPCS#登录网盘 ，可以使用 'pcs set --captcha_file=/var/www/html/captcha.gif' 来指定路径
