### ISSUE TITLE
无法登录，提示wrong captcha

### ISSUE THREAD

**Issue by 4321qasdfv** [GangZhuo/BaiduPCS#80]
我用的windows下gui版
现在验证码都是中文的了，所以不可能输错
但是不论输什么，都是弹4次验证码以后提示验证码错误
我在网页上登录就是正常的，输一次验证码就进去了
这是怎么回事

**Comment by GangZhuo** [comment]
应该是中文编码的问题，空的时候调试看看

**Comment by BlackHole1** [comment]
请问这个bug解决了么？中文的验证码无法登陆。如果吧cookies保存到文件里，也不清楚格式。可以像这样把cookies写进去么：H_PS_PSSID=20xxxxxxxxxxxxxxxxxxxxxxxx40_21127_21192_21160; BDCLND=rdRhAN2xxxxxxxxxxxxxxxxxxxxxxxxxxxH2u0XOdGhO%2FY%3D; TOPMSG=14xxxxxxxx43-0; Hm_lvt_7a3960xxxxxxxxx6ff5e660b0=1xxx18155,14xxxxx9890,147xxx0411,14xxx4; Hm_lpvt_7a396xxxxxxxxxxxxxxxxxxb7f96ff5e660b0=147xxxx889; cflag=13xxx3

**Comment by GangZhuo** [comment]
See https://github.com/GangZhuo/BaiduPCS/issues/62#issuecomment-251395932

**Comment by celeron533** [comment]
中文验证码测试（直接terminal，非SSH） https://github.com/GangZhuo/BaiduPCS/issues/78#issuecomment-251381089

**Comment by nuclearn** [comment]
碰到这种情况，无法登入，试了cookie方法叶不行。

**Comment by GangZhuo** [comment]
测试中文验证码可以输入，如果正确输入后，还是提示错误的话，请检查一下 putty 等 ssh 客户端的编码是否设置为 UTF-8了。

**Comment by nuclearn** [comment]
今天的代码已经可以登入了，赞！

**Comment by GangZhuo** [comment]
嗯，之前确实是windows 下不能输入中文验证码，平时在家使用的是 debian 系统，因此未注意到有这个问题。
