### ISSUE TITLE
不能登录，需要输入手机验证码

### ISSUE THREAD

**Issue by 786259135** [GangZhuo/BaiduPCS#83]
User Name: xxxxx
Password:
The captcha image at C:\Users\Passer.pcs\captcha.gif.
Please input the captcha code: 松涛
Login Failed: error: 7 Wrong password, try sms password

PCS命令行以及.net版均无法登录

**Comment by GangZhuo** [comment]
密码输错了

**Comment by 786259135** [comment]
密码没错，但是需要输入手机验证码，我直接在PC上登录也需要，如果密码错了，不会出现验手机证码

**Comment by GangZhuo** [comment]
你在浏览器中修改一下密码再试看看，需要手机验证码的错误号不是 7。错误号 7 的意思应该是密码错了，可以使用手机密码来代替登录。

**Comment by GangZhuo** [comment]
错误码参考 https://github.com/GangZhuo/BaiduPCS/blob/master/pcs/err_msg.c#L38

**Comment by 786259135** [comment]
我用刚才登录账户的密码去找回密码，百度告诉我新密码不能与老密码相同，密码没有错

我的账号有绑定手机以及邮箱

**Comment by GangZhuo** [comment]
你系统环境是什么？

**Comment by 786259135** [comment]
Win7 x64 + Google Chrome 版本 53.0.2785.143 m (64-bit)

**Comment by 786259135** [comment]
账户频繁异地登录，可能受此影响需要输入手机验证码

**Comment by 0oVicero0** [comment]
windows版需要手机验证码，没有框框输入，手机已经收到验证码了

**Comment by GangZhuo** [comment]
@0oVicero0 是有界面的版本吗？能截图吗？或者界面提示什么？

**Comment by 0oVicero0** [comment]
![default](https://cloud.githubusercontent.com/assets/11154604/19719438/80f4be4c-9b9c-11e6-9ab9-2ebc846d8bc5.PNG)
点击登陆，输入完图片验证码，之后，手机就受到了一条短信，短信内容为手机验证码，然后，这张图片就错误提示.

**Comment by GangZhuo** [comment]
@0oVicero0 try 1.0.4  https://github.com/GangZhuo/BaiduPCS_NET/releases

**Comment by 0oVicero0** [comment]
还是一样的。
会不会要安装什么依赖？
![default](https://cloud.githubusercontent.com/assets/11154604/19722679/5da2d15a-9baa-11e6-8bf7-42b77596f4c0.PNG)

**Comment by GangZhuo** [comment]
不是依赖的问题，等我这边能重现这个问题，再调试看看吧。你现在可以用浏览器登录一次，然后应该就可以了。

**Comment by 0oVicero0** [comment]
浏览器重新登陆，就可以了。
另外建议一下， 是否可以直接调用 IDM 或者 Aria2c ?
自带的下载器，好像不怎么给力

**Comment by 0oVicero0** [comment]
![1](https://cloud.githubusercontent.com/assets/11154604/19723833/c938ba4c-9baf-11e6-8523-abe1d186dcbc.PNG)
是我的网络问题吗？
挂了V-P-N ,也还是错误

**Comment by 786259135** [comment]
![qq 20161026204205](https://cloud.githubusercontent.com/assets/16495257/19726275/afe2a73a-9bbc-11e6-8a27-584b0eb9e32c.png)
我直接在浏览器上登录，也是需要验证码的

**Comment by GangZhuo** [comment]
看起来像是文件写不进去。直接用命令行版本或者换其他工具吧。

.Vicer <notifications@github.com>于2016年10月26日周三 下午7:12写道：

**Comment by GangZhuo** [comment]
外部程序获取不到 cookie,不能下载。

.Vicer <notifications@github.com>于2016年10月26日周三 下午7:03写道：

**Comment by masahoshiro** [comment]
同样，登录输入验证码后提示如下，程序是直接退出的，同时接到验证码短信 `【百度】您在百度请求的验证码是：xxxxxx`

在自己的 VPS 上测试的（也许是异地？）
Ubuntu 16.04


`The captcha image at /root/.pcs/captcha.gif.
Please input the captcha code: ...
Login Failed: Failed to send sms: 
`

**Comment by sidney9111** [comment]
百度2016净网行动，你们这么看，我很多视频都已经下载不了了，这个API什么时候会给封

**Comment by wnpllrzodiac** [comment]
照这趋势，网盘关闭是早晚的事。免费的事做多了，就没意思了。 发自网易邮箱大师 在2016年10月29日 11:23 ，sidney9111写道： 百度2016净网行动，你们这么看，我很多视频都已经下载不了了，这个API什么时候会给封 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by ACGunion** [comment]
能提供一下如何用cookie登陆吗。现在需要输入短信验证吗，但是没有地方输入。
Login Failed: Failed to send sms: 
（我的账户并没有开启短信验证）

**Comment by chijiao** [comment]
我也是遇到这个问题, 提示要输入手机验证码. 应该是检查到了我是异地登录, 会发送一个短信验证码过来,可是这个没有地方输入短信验证码,导致无法登录. 我想问的是, 能不能把浏览器的cookie导出来, 直接用浏览器的cookie来登录

**Comment by GangZhuo** [comment]
via https://github.com/GangZhuo/BaiduPCS/commit/e1c2a1935e57e0eb167fa735d02db72c40021ca5
