### ISSUE TITLE
不错的功能，但是修改代码无效？说不能登录的，百度有疑似被盗安全验证，先去百度输入手机验证码即可

### ISSUE THREAD

**Issue by sidney9111** [GangZhuo/BaiduPCS#84]
我改了代码后，编译后的运行结果没更新
有缓存么？（每次都不要重新登录，这个估计cookie的原因）
我加了一些log，修改了一些本来的log，编译后没正确运行
我重启macos还是不行
确定编译的.c文件和编译过程是正确的
exec怎么结束
还是什么问题？

**Comment by sidney9111** [comment]
哦，找到原因了，漏了 make install

**Comment by GangZhuo** [comment]
make 之后，生成的文件在源码同目录下的 bin 目录中，因此可以使用  ./bin/pcs download ... 这样的命令来测试。
