### ISSUE TITLE
真实下载地址

### ISSUE THREAD

**Issue by yknext** [GangZhuo/BaiduPCS#85]
是否能在下载文件的时候打印出文件真实下载地址，
方便用迅雷或者其他工具下载特别大的文件，百度云的速度比较慢

**Comment by wnpllrzodiac** [comment]
建议用和谐版百度桌面端。单线程下载资源速度非常不理想。除非开通vip. 发自网易邮箱大师 在2016年10月24日 17:05 ，yknext写道： 是否能在下载文件的时候打印出文件真实下载地址， 方便用迅雷或者其他工具下载特别大的文件，百度云的速度比较慢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by yknext** [comment]
目前用了 tampermonkey  加上一个插件（https://greasyfork.org/zh-CN/scripts/23635-%E7%99%BE%E5%BA%A6%E4%BA%91%E7%9B%B4%E6%8E%A5%E4%B8%8B%E8%BD%BD/code），可以获取真实地址了
