### ISSUE TITLE
碰到400031错误（估计是 baidu-passport 的锅）

### ISSUE THREAD

**Issue by rambolee** [GangZhuo/BaiduPCS#87]
```shell
The captcha image at /Users/libo/.pcs/captcha.gif.
Please input the captcha code: 几天
Login Failed: error: 400031 Try again
```

多次尝试都是这个错误。

参考其他 #83 中的提示错误码参考
https://github.com/GangZhuo/BaiduPCS/blob/master/pcs/err_msg.c#L26

已经尝试重新登录。没有碰到什么弹出窗口。

请问这个怎么处理。

**Comment by GangZhuo** [comment]
这个估计要自己调试看看了，我这边遇不到这个错，没有办法调试的。如果你是在远程服务器上登录的话，可以尝试把本地的 cookie 文件复制到远程服务器上，然后调用 pcs who 看看是不是已经登录了。cookie 文件的路径可以通过 pcs context 命令来查看。

**Comment by rambolee** [comment]
查阅了一下其他百度系的产品的一些资料。应该是，这个 error 需要百度的 passport 发送一个验证短信。
但是，我反复多次也没有收到发过来的短信（需要回复大写的'Y'）。

这个问题，我自己再追一下。多谢答复。
