### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [GangZhuo/BaiduPCS#90]
I would like to point out that identifiers like "[`_PCS_SHELL_SHELL_H`](https://github.com/GangZhuo/BaiduPCS/blob/3ce5372e4f0e898f79e160984799e71a313428b8/shell.h#L1)" and "[`_VERSION_H`](https://github.com/GangZhuo/BaiduPCS/blob/8455db368e717b6e26abd99e7415588bd365f434/version.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by GangZhuo** [comment]
PR is welcome.

Markus Elfring <notifications@github.com>于2016年10月27日周四 下午9:17写道：
