### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [GangZhuo/BaiduPCS#91]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html) ⇒ [pcs_mem_malloc](https://github.com/GangZhuo/BaiduPCS/blob/c59187f5bce774ae5d801cc6a249f5d09f75f219/pcs/pcs_mem.c#L56)
- [printf](http://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html) ⇒ [cmd_who](https://github.com/GangZhuo/BaiduPCS/blob/1d39f9bfbd427dbf56b812608f0137b58864ea81/shell.c#L6559)

**Comment by GangZhuo** [comment]
PR is welcome.

Markus Elfring <notifications@github.com>于2016年10月27日周四 下午9:32写道：
