### ISSUE TITLE
pcs: error while loading shared libraries: libcrypto.so.1.0.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ghostry** [GangZhuo/BaiduPCS#93]
pcs: error while loading shared libraries: libcrypto.so.1.0.2: cannot open shared object file: No such file or directory

**Comment by GangZhuo** [comment]
看 readme 中的 Windows 下编译方法部分

ghostry <notifications@github.com>于2016年11月9日周三 下午4:11写道：

**Comment by GangZhuo** [comment]
https://github.com/GangZhuo/BaiduPCS#2-安装依赖-baidupcs-dependencieszip
